# Paladin: defensive spells, utility, offensive spells, talent abilities.
from common import *

ABILITIES, AURAS = [], []


def PA(*a, **k):
    ABILITIES.append(make_ability("Paladin", *a, **k))


def AU(*a, **k):
    AURAS.append(make_aura(*a, **k))


# ------------------------------------------------------------- defensive
LOH_R = [10, 30, 50]
PA("paladin_lay_on_hands", "Lay on Hands", "hands_pray", "Holy",
   "Heals a friendly target for an amount equal to the Paladin's maximum health and drains all of the Paladin's "
   "remaining mana. Rank 2 also restores 250 mana to the target, rank 3 restores 550.", 10, LOH_R,
   cooldown=3600, cost={"type": "Mana", "consumeAll": True}, target="Ally", range=40,
   effects=[E("Special", special="PaladinLayOnHands")], tags=["Heal"], aiHint="Heal", aiPriority=9)

DP_R = [6, 18]
PA("paladin_divine_protection", "Divine Protection", "shield", "Holy",
   "You are protected from all physical attacks and spells for 6 sec (rank 2: 8 sec), but during that time you "
   "cannot attack or use physical abilities. Causes Forbearance for 1 min.", 6, DP_R,
   cooldown=300, cost=cost(35, 50, DP_R), target="Self",
   effects=[apply("paladin_divine_protection", target="Self", duration=6, perLevel=pl(6, 8, 6, 18)),
            apply("paladin_forbearance", target="Self")],
   special="PaladinForbearanceCheck", aiHint="Defensive", aiPriority=8)
AU("paladin_divine_protection", "Divine Protection", "shield", "Buff", "Holy",
   "Immune to all damage and harmful effects; cannot attack or use physical abilities.", 6,
   states=["Invulnerable", "Pacify"])

DS_R = [34, 50]
PA("paladin_divine_shield", "Divine Shield", "shield", "Holy",
   "Protects the Paladin from all damage and spells for 10 sec (rank 2: 12 sec), but reduces attack speed by 50%. "
   "Causes Forbearance for 1 min.", 34, DS_R,
   cooldown=300, cost=cost(75, 110, DS_R), target="Self",
   effects=[apply("paladin_divine_shield", target="Self", duration=10, perLevel=pl(10, 12, 34, 50)),
            apply("paladin_forbearance", target="Self")],
   special="PaladinForbearanceCheck", aiHint="Defensive", aiPriority=9)
AU("paladin_divine_shield", "Divine Shield", "shield", "Buff", "Holy",
   "Immune to all damage and harmful effects. Attack speed reduced by 50%.", 10,
   states=["Invulnerable"], mods=[M("MeleeHaste", -50, pct=True)])

PA("paladin_righteous_fury", "Righteous Fury", "sun", "Holy",
   "Increases the threat generated by your Holy spells by 60% for 30 min.", 16,
   cost=cost(80), target="Self", effects=[apply("paladin_righteous_fury", target="Self")],
   tags=["Buff"], aiHint="Buff", aiPriority=2)
AU("paladin_righteous_fury", "Righteous Fury", "sun", "Buff", "Holy",
   "Threat generated by Holy spells increased by 60%.", 1800, mods=[M("ThreatGenerated", 60, pct=True, school="Holy")])

DI_R = [30]
PA("paladin_divine_intervention", "Divine Intervention", "wings", "Holy",
   "The Paladin sacrifices himself to remove the targeted party member from harm's way. Enemies will stop attacking "
   "the protected party member, who will be immune to all harmful attacks but cannot take any action for 3 min. "
   "Drains all of the Paladin's mana.", 30,
   cooldown=3600, cost={"type": "Mana", "consumeAll": True}, target="AllyOther", range=30,
   effects=[apply("paladin_divine_intervention"), E("Special", special="PaladinDivineIntervention")],
   aiHint="Utility", aiPriority=1)
AU("paladin_divine_intervention", "Divine Intervention", "wings", "Buff", "Holy",
   "Protected by Divine Intervention: immune to all harm, cannot act, ignored by enemies.", 180,
   states=["Banish", "Invulnerable"], persistThroughDeath=False)

# --------------------------------------------------------------- utility
HOJ_R = [8, 24, 40, 54]
PA("paladin_hammer_of_justice", "Hammer of Justice", "hammer", "Holy",
   "Stuns the target for 3 sec (rank 2: 4, rank 3: 5, rank 4: 6 sec).", 8, HOJ_R,
   cooldown=60, cost=cost(30, 90, HOJ_R), target="Enemy", range=10,
   effects=[apply("paladin_hammer_of_justice", duration=3, perLevel=pl(3, 6, 8, 54))],
   tags=["Stun"], aiHint="CC", aiPriority=6)
AU("paladin_hammer_of_justice", "Hammer of Justice", "hammer", "Debuff", "Holy", "Stunned.", 3,
   dispel="Magic", states=["Stun"], tags=["Stun"])

PA("paladin_purify", "Purify", "hand", "Holy",
   "Cleanses a friendly target, removing 1 poison effect and 1 disease effect.", 8,
   cost=cost(32), target="Ally", range=30,
   effects=[E("Dispel", dispelType="Poison", dispelCount=1), E("Dispel", dispelType="Disease", dispelCount=1)],
   aiHint="Utility", aiPriority=5)

PA("paladin_cleanse", "Cleanse", "hand", "Holy",
   "Cleanses a friendly target, removing 1 poison effect, 1 disease effect and 1 magic effect.", 42,
   cost=cost(60), target="Ally", range=30,
   effects=[E("Dispel", dispelType="Magic", dispelCount=1), E("Dispel", dispelType="Poison", dispelCount=1),
            E("Dispel", dispelType="Disease", dispelCount=1)],
   aiHint="Utility", aiPriority=6)

RED_R = [12, 24, 36, 48, 60]
PA("paladin_redemption", "Redemption", "hands_pray", "Holy",
   "Brings a dead player back to life with 35% health and mana.", 12, RED_R,
   castTime=10, cost=cost(125, 1110, RED_R), target="DeadAlly", range=30,
   effects=[E("Resurrect", pctOfMax=35)], aiHint="Utility", aiPriority=8)

TU_R = [24, 38, 50]
PA("paladin_turn_undead", "Turn Undead", "sun", "Holy",
   "The targeted undead enemy will be compelled to flee for up to 10 sec (rank 2: 15, rank 3: 20 sec). Damage caused "
   "may interrupt the effect. Only one target can be turned at a time.", 24, TU_R,
   castTime=1.5, cooldown=30, cost=cost(50, 140, TU_R), target="Enemy", range=20,
   requires={"targetCreatureTypes": ["Undead"]},
   effects=[apply("paladin_turn_undead", duration=10, perLevel=pl(10, 20, 24, 50))], aiHint="CC", aiPriority=4)
AU("paladin_turn_undead", "Turn Undead", "fear", "Debuff", "Holy", "Fleeing in terror.", 10,
   dispel="Magic", exclusiveGroup="paladin_turn_undead", exclusivePerCaster=True, states=["Fear"], tags=["Fear"])

# ------------------------------------------------------------- offensive
EXO_R = [20, 28, 36, 44, 52, 60]
PA("paladin_exorcism", "Exorcism", "holy", "Holy",
   "Causes {0} Holy damage to an Undead or Demon target.", 20, EXO_R,
   cooldown=15, cost=cost(85, 345, EXO_R), target="Enemy", range=30,
   requires={"targetCreatureTypes": ["Undead", "Demon"]},
   effects=[dmg(90, 102, 505, 563, EXO_R, coef=0.429)], aiHint="Damage", aiPriority=7)

HOW_R = [44, 52, 60]
PA("paladin_hammer_of_wrath", "Hammer of Wrath", "hammer", "Holy",
   "Hurls a hammer that strikes an enemy for {0} Holy damage. Only usable on enemies that have 20% or less health.",
   44, HOW_R, castTime=1.0, cooldown=6, cost=cost(295, 435, HOW_R), target="Enemy", range=30,
   requires={"targetHealthBelowPct": 20},
   effects=[dmg(304, 336, 504, 556, HOW_R, coef=0.429)], aiHint="Damage", aiPriority=8)

HW_R = [50, 60]
PA("paladin_holy_wrath", "Holy Wrath", "sun", "Holy",
   "Sends bolts of holy power in all directions, causing {0} Holy damage to all Undead and Demon targets within "
   "20 yards.", 50, HW_R, castTime=2.0, cooldown=60, cost=cost(645, 805, HW_R), target="Self",
   area={"shape": "Circle", "radius": 20, "centeredOnCaster": True, "affects": "Enemies"},
   requires={"targetCreatureTypes": ["Undead", "Demon"]},
   effects=[dmg(362, 428, 490, 576, HW_R, coef=0.19)], aiHint="AoE", aiPriority=5)

# ------------------------------------------------------- talent abilities
CON_R = [20, 30, 40, 50, 60]
PA("paladin_consecration", "Consecration", "sun", "Holy",
   "Consecrates the land beneath the Paladin, doing 64 (rank 5: 384) Holy damage over 8 sec to enemies who enter "
   "the area.", 20, CON_R, fromTalent=True, cooldown=8, cost=cost(135, 565, CON_R), target="Self",
   effects=[apply("paladin_consecration", target="Self")], aiHint="AoE", aiPriority=5)
AU("paladin_consecration", "Consecration", "sun", "Buff", "Holy",
   "Consecrated ground: enemies within 8 yards take Holy damage every second.", 8,
   tags=["Consecration"], radius=8, radiusAura="paladin_consecration_effect", radiusAffects="Enemies")
AU("paladin_consecration_effect", "Consecration", "sun", "Debuff", "Holy", "Taking Holy damage every second.", 0,
   tags=["Consecration"], tickInterval=1,
   tickEffects=[E("Damage", school="Holy", min=8, perLevel=pl(8, 48, 20, 60), coef=0.042)])

HS_R = [40, 48, 56]
PA("paladin_holy_shock", "Holy Shock", "holy", "Holy",
   "Blasts the target with Holy energy, causing {0} Holy damage to an enemy, or {1} healing to an ally.", 40, HS_R,
   fromTalent=True, cooldown=30, cost=cost(225, 325, HS_R), target="Any", range=20,
   effects=[dmg(204, 220, 365, 395, HS_R, coef=0.429), heal(204, 220, 365, 395, HS_R, coef=0.429)],
   tags=["Heal"], special="PaladinHolyShock", aiHint="Heal", aiPriority=7)

HSH_R = [40, 50, 60]
PA("paladin_holy_shield", "Holy Shield", "shield", "Holy",
   "Increases chance to block by 30% for 10 sec, and deals 65 (rank 3: 130) Holy damage for each attack blocked "
   "while active. Each block expends a charge. 4 charges.", 40, HSH_R,
   fromTalent=True, cooldown=10, cost=cost(135, 215, HSH_R), target="Self", requires={"shield": True},
   effects=[apply("paladin_holy_shield", target="Self")], aiHint="Defensive", aiPriority=6)
AU("paladin_holy_shield", "Holy Shield", "shield", "Buff", "Holy",
   "Block chance increased by 30%. Blocked attackers take Holy damage.", 10, dispel="Magic", charges=4,
   mods=[M("Block", 30)],
   procs=[proc("OnBlock", [E("Damage", target="Attacker", school="Holy", min=65, perLevel=pl(65, 130, 40, 60),
                             coef=0.05)], consumeCharge=True)])

PA("paladin_repentance", "Repentance", "hands_pray", "Holy",
   "Puts the enemy target in a state of meditation, incapacitating it for up to 6 sec. Any damage caused will awaken "
   "the target. Only works against Humanoids.", 40, fromTalent=True,
   cooldown=60, cost=cost(60), target="Enemy", range=20, requires={"targetCreatureTypes": ["Humanoid"]},
   effects=[apply("paladin_repentance")], aiHint="CC", aiPriority=5)
AU("paladin_repentance", "Repentance", "hands_pray", "Debuff", "Holy", "Incapacitated.", 6,
   dispel="Magic", states=["Incapacitate"], breakOnDamage=True)

PA("paladin_divine_favor", "Divine Favor", "star", "Holy",
   "When activated, gives your next Flash of Light, Holy Light, or Holy Shock spell a 100% critical effect chance. "
   "Does not trigger the global cooldown.", 30, fromTalent=True,
   time="OffGcd", cooldown=120, cost={"type": "Mana", "pctBaseMana": 3}, target="Self",
   effects=[apply("paladin_divine_favor", target="Self")], aiHint="Buff", aiPriority=6)
AU("paladin_divine_favor", "Divine Favor", "star", "Buff", "Holy",
   "Your next Flash of Light, Holy Light or Holy Shock is a critical effect.", 0, charges=1,
   procs=[proc("OnSpellCast", [], abilities=["paladin_holy_light", "paladin_flash_of_light", "paladin_holy_shock"],
               consumeCharge=True)],
   special="PaladinDivineFavor")   # forced crit only for the spells of the consuming proc

PA("paladin_parry", "Parry", "swords", "Physical", "Gives a chance to parry enemy melee attacks made from the front.",
   8, trainCost=200, passive=True)

# ---------------------------------------------------------------- passive
PA("paladin_plate_mail", "Plate Mail", "armor", "Physical",
   "Allows the wearing of plate armor (trained at level 40).", 40, passive=True)
