# Priest talent trees (WoW Classic 1.12) and talent-proc auras.
from common import *

AURAS = []
T = talent
MAGIC = ["Holy", "Fire", "Nature", "Frost", "Shadow", "Arcane"]


def d(n):
    return "priest_discipline_" + n


def h(n):
    return "priest_holy_" + n


def s(n):
    return "priest_shadow_" + n


def pr(*names):
    return ["priest_" + n for n in names]


INSTANT = pr("power_word_shield", "power_word_fortitude", "prayer_of_fortitude", "renew", "shadow_word_pain",
             "psychic_scream", "fade", "dispel_magic", "cure_disease", "abolish_disease", "holy_nova", "inner_fire",
             "shadow_protection", "divine_spirit", "power_infusion", "silence", "vampiric_embrace", "shadowform",
             "fear_ward", "feedback", "mind_soothe")
OFFENSIVE = pr("smite", "holy_fire", "mind_blast", "shadow_word_pain", "mind_flay", "holy_nova", "mana_burn")

DISC = {
    "id": "tree_priest_discipline", "classId": "Priest", "name": "Discipline", "icon": "halo",
    "description": "Willpower, shields, mana efficiency and empowering allies.",
    "talents": [
        T(d("unbreakable_will"), "Unbreakable Will", "cross", 1, 1, 5,
          "Increases your chance to resist Stun, Fear, and Silence effects by an additional {3/6/9/12/15}%.",
          [P_special("PriestUnbreakableWill", values=[3, 6, 9, 12, 15])]),
        T(d("wand_specialization"), "Wand Specialization", "staff", 1, 2, 5,
          "Increases your damage with Wands by {5/10/15/20/25}%.", [P_mod("Damage", 5, abilities=["shoot"])]),
        T(d("silent_resolve"), "Silent Resolve", "hands_pray", 2, 0, 5,
          "Reduces the threat generated by your Holy and Discipline spells by {4/8/12/16/20}% and reduces the chance "
          "your helpful spells and damage over time effects will be dispelled by {4/8/12/16/20}%.",
          [P_mod("Threat", -4, schools=["Holy"])]),
        T(d("improved_power_word_fortitude"), "Improved Power Word: Fortitude", "heart", 2, 1, 2,
          "Increases the effect of your Power Word: Fortitude and Prayer of Fortitude spells by {15/30}%.",
          [P_mod("Effect", 15, abilities=pr("power_word_fortitude", "prayer_of_fortitude"))]),
        T(d("improved_power_word_shield"), "Improved Power Word: Shield", "shield", 2, 2, 3,
          "Increases damage absorbed by your Power Word: Shield by {5/10/15}%.",
          [P_mod("Effect", 5, abilities=pr("power_word_shield"))]),
        T(d("martyrdom"), "Martyrdom", "heart", 2, 3, 2,
          "Gives you a {50/100}% chance to gain the Focused Casting effect that lasts for 6 sec after being the victim "
          "of a melee or ranged critical strike. The Focused Casting effect prevents you from losing casting time when "
          "taking damage and increases resistance to Interrupt effects by {10/20}%.",
          [P_proc(proc("OnCritTaken", [apply("priest_focused_casting", target="Self")], chance=50,
                       schools=["Physical"]), values=[50, 100])]),
        T(d("inner_focus"), "Inner Focus", "eye", 3, 1, 1,
          "When activated, reduces the mana cost of your next spell by 100% and increases its critical effect chance "
          "by 25% if it is capable of a critical effect.", [P_grant("priest_inner_focus")]),
        T(d("meditation"), "Meditation", "hands_pray", 3, 2, 3,
          "Allows {5/10/15}% of your Mana regeneration to continue while casting.",
          [P_stat("SpiritRegenWhileCasting", 5)]),
        T(d("improved_inner_fire"), "Improved Inner Fire", "sun", 4, 0, 3,
          "Increases the effect of your Inner Fire spell by {10/20/30}%.",
          [P_mod("Effect", 10, abilities=pr("inner_fire"))]),
        T(d("mental_agility"), "Mental Agility", "brain", 4, 1, 5,
          "Reduces the mana cost of your instant cast spells by {2/4/6/8/10}%.",
          [P_mod("Cost", -2, abilities=INSTANT)]),
        T(d("improved_mana_burn"), "Improved Mana Burn", "drain", 4, 3, 2,
          "Reduces the casting time of your Mana Burn spell by {0.25/0.5} secs.",
          [P_mod("CastTime", -0.25, abilities=pr("mana_burn"))]),
        T(d("mental_strength"), "Mental Strength", "brain", 5, 1, 5,
          "Increases your maximum Mana by {2/4/6/8/10}%.", [P_stat("Mana", 2, pct=True)]),
        T(d("divine_spirit"), "Divine Spirit", "halo", 5, 2, 1,
          "Holy power infuses the target, increasing their Spirit by 23 for 30 min.",
          [P_grant("priest_divine_spirit")], requires=d("meditation")),
        T(d("force_of_will"), "Force of Will", "star", 6, 2, 5,
          "Increases your spell damage by {1/2/3/4/5}% and the critical strike chance of your offensive spells by "
          "{1/2/3/4/5}%.",
          [P_mod("Damage", 1, abilities=OFFENSIVE), P_mod("CritChance", 1, abilities=OFFENSIVE)]),
        T(d("power_infusion"), "Power Infusion", "star", 7, 1, 1,
          "Infuses the target with power, increasing their spell damage and healing by 20%. Lasts 15 sec.",
          [P_grant("priest_power_infusion")], requires=d("mental_strength")),
    ],
}

HOLY = {
    "id": "tree_priest_holy", "classId": "Priest", "name": "Holy", "icon": "holy",
    "description": "Healing, holy damage and the light that outlasts death.",
    "talents": [
        T(h("healing_focus"), "Healing Focus", "hands_pray", 1, 0, 2,
          "Gives you a {35/70}% chance to avoid interruption caused by damage while casting any healing spell.",
          [P_special("PriestPushbackResist", values=[35, 70])]),
        T(h("improved_renew"), "Improved Renew", "renew", 1, 1, 3,
          "Increases the amount healed by your Renew spell by {5/10/15}%.",
          [P_mod("Effect", 5, abilities=pr("renew"))]),
        T(h("holy_specialization"), "Holy Specialization", "holy", 1, 2, 5,
          "Increases the critical effect chance of your Holy spells by {1/2/3/4/5}%.",
          [P_stat("SpellCrit", 1, school="Holy")]),
        T(h("spell_warding"), "Spell Warding", "shield", 2, 1, 5,
          "Reduces all spell damage taken by {2/4/6/8/10}%.",
          [P_stat("DamageTaken", -2, pct=True, school=x) for x in MAGIC]),
        T(h("divine_fury"), "Divine Fury", "sun", 2, 2, 5,
          "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by "
          "{0.1/0.2/0.3/0.4/0.5} sec.",
          [P_mod("CastTime", -0.1, abilities=pr("smite", "holy_fire", "heal", "greater_heal"))]),
        T(h("holy_nova"), "Holy Nova", "sun", 3, 0, 1,
          "Causes an explosion of holy light around the caster, causing 29 to 34 Holy damage to all enemy targets "
          "within 10 yards and healing all party members within 10 yards for 52 to 60. These effects cause no threat.",
          [P_grant("priest_holy_nova")]),
        T(h("blessed_recovery"), "Blessed Recovery", "heal_plus", 3, 1, 3,
          "After being struck by a melee or ranged critical hit, heal {8/16/25}% of the damage taken over 6 sec.",
          [P_proc(proc("OnCritTaken", [E("Special", target="Self", special="PriestBlessedRecovery")],
                       schools=["Physical"]))]),
        T(h("inspiration"), "Inspiration", "armor", 3, 3, 3,
          "Increases your target's armor by {8/16/25}% for 15 sec after getting a critical effect from your Flash "
          "Heal, Heal, Greater Heal, or Prayer of Healing spell.",
          [P_proc(proc("OnSpellCrit", [apply("priest_inspiration")],
                       abilities=pr("flash_heal", "heal", "greater_heal", "prayer_of_healing")))]),
        T(h("holy_reach"), "Holy Reach", "holy", 4, 0, 2,
          "Increases the range of your Smite and Holy Fire spells by {10/20}%.",
          [P_mod("Range", 10, abilities=pr("smite", "holy_fire"))]),
        T(h("improved_healing"), "Improved Healing", "heal_plus", 4, 1, 3,
          "Reduces the Mana cost of your Lesser Heal, Heal, and Greater Heal spells by {5/10/15}%.",
          [P_mod("Cost", -5, abilities=pr("lesser_heal", "heal", "greater_heal"))]),
        T(h("searing_light"), "Searing Light", "fire", 4, 2, 2,
          "Increases the damage of your Smite and Holy Fire spells by {5/10}%.",
          [P_mod("Damage", 5, abilities=pr("smite", "holy_fire"))]),
        T(h("improved_prayer_of_healing"), "Improved Prayer of Healing", "hands_pray", 5, 0, 2,
          "Reduces the Mana cost of your Prayer of Healing spell by {10/20}%.",
          [P_mod("Cost", -10, abilities=pr("prayer_of_healing"))]),
        T(h("spirit_of_redemption"), "Spirit of Redemption", "wings", 5, 1, 1,
          "Upon death, the priest becomes the Spirit of Redemption for 10 sec. The Spirit of Redemption cannot move, "
          "attack, be attacked or targeted by any spells or effects. While in this form the priest can cast any "
          "healing spell free of cost. When the effect ends, the priest dies.",
          [P_grant("priest_spirit_of_redemption")]),
        T(h("spiritual_guidance"), "Spiritual Guidance", "halo", 5, 2, 5,
          "Increases spell damage and healing by up to {5/10/15/20/25}% of your total Spirit.",
          [P_special("PriestSpiritualGuidance", values=[5, 10, 15, 20, 25])]),
        T(h("spiritual_healing"), "Spiritual Healing", "heal_plus", 6, 2, 5,
          "Increases the amount healed by your healing spells by {2/4/6/8/10}%.",
          [P_stat("HealingDone", 2, pct=True)]),
        T(h("lightwell"), "Lightwell", "halo", 7, 1, 1,
          "Creates a holy Lightwell. Members of your party can use the Lightwell to be healed for 800 over 10 sec. "
          "Lightwell lasts 3 min or 5 charges.", [P_grant("priest_lightwell")], requires=h("spirit_of_redemption")),
    ],
}

SHADOW = {
    "id": "tree_priest_shadow", "classId": "Priest", "name": "Shadow", "icon": "shadow",
    "description": "Shadow magic, damage over time and mind control.",
    "talents": [
        T(s("spirit_tap"), "Spirit Tap", "soul_shard", 1, 1, 5,
          "Gives you a {20/40/60/80/100}% chance to gain a 100% bonus to your Spirit after killing a target that yields "
          "experience. For the duration, your Mana will regenerate at a 50% rate while casting. Lasts 15 sec.",
          [P_proc(proc("OnKill", [apply("priest_spirit_tap", target="Self")], chance=20),
                  values=[20, 40, 60, 80, 100])]),
        T(s("blackout"), "Blackout", "shadow", 1, 2, 5,
          "Gives your Shadow damage spells a {2/4/6/8/10}% chance to stun the target for 3 sec.",
          [P_proc(proc("OnSpellHit", [apply("priest_blackout")], chance=2, schools=["Shadow"]),
                  values=[2, 4, 6, 8, 10])]),
        T(s("shadow_affinity"), "Shadow Affinity", "shadow", 2, 0, 3,
          "Reduces the threat generated by your Shadow spells by {8/16/25}%.",
          [P_mod("Threat", values=[-8, -16, -25], schools=["Shadow"])]),
        T(s("improved_shadow_word_pain"), "Improved Shadow Word: Pain", "skull", 2, 1, 2,
          "Increases the duration of your Shadow Word: Pain spell by {3/6} sec.",
          [P_mod("Duration", 3, abilities=pr("shadow_word_pain"))]),
        T(s("shadow_focus"), "Shadow Focus", "eye", 2, 2, 5,
          "Reduces your target's chance to resist your Shadow spells by {2/4/6/8/10}%.",
          [P_stat("SpellHit", 2, school="Shadow")]),
        T(s("improved_psychic_scream"), "Improved Psychic Scream", "fear", 3, 0, 2,
          "Reduces the cooldown of your Psychic Scream spell by {2/4} sec.",
          [P_mod("Cooldown", -2, abilities=pr("psychic_scream"))]),
        T(s("improved_mind_blast"), "Improved Mind Blast", "brain", 3, 1, 5,
          "Reduces the cooldown of your Mind Blast spell by {0.5/1/1.5/2/2.5} sec.",
          [P_mod("Cooldown", -0.5, abilities=pr("mind_blast"))]),
        T(s("mind_flay"), "Mind Flay", "tentacle", 3, 2, 1,
          "Assault the target's mind with Shadow energy, causing 75 Shadow damage over 3 sec and slowing their "
          "movement speed by 50%.", [P_grant("priest_mind_flay")]),
        T(s("improved_fade"), "Improved Fade", "stealth", 4, 1, 2,
          "Decreases the cooldown of your Fade ability by {3/6} sec.",
          [P_mod("Cooldown", -3, abilities=pr("fade"))]),
        T(s("shadow_reach"), "Shadow Reach", "shadow", 4, 2, 3,
          "Increases the range of your Shadow damage spells by {6/13/20}%.",
          [P_mod("Range", values=[6, 13, 20], schools=["Shadow"])]),
        T(s("shadow_weaving"), "Shadow Weaving", "void", 4, 3, 5,
          "Your Shadow damage spells have a {20/40/60/80/100}% chance to cause your target to be vulnerable to Shadow "
          "damage. This vulnerability increases the Shadow damage dealt to your target by 3% and lasts 15 sec. Stacks "
          "up to 5 times.",
          [P_proc(proc("OnSpellHit", [apply("priest_shadow_vulnerability")], chance=20, schools=["Shadow"]),
                  values=[20, 40, 60, 80, 100])]),
        T(s("silence"), "Silence", "mask", 5, 0, 1,
          "Silences the target, preventing them from casting spells for 5 sec.", [P_grant("priest_silence")],
          requires=s("improved_psychic_scream")),
        T(s("vampiric_embrace"), "Vampiric Embrace", "blood", 5, 1, 1,
          "Afflicts your target with Shadow energy that causes all party members to be healed for 20% of any Shadow "
          "spell damage you deal. Lasts 1 min.", [P_grant("priest_vampiric_embrace")]),
        T(s("improved_vampiric_embrace"), "Improved Vampiric Embrace", "blood", 5, 2, 2,
          "Increases the percentage healed by Vampiric Embrace by an additional {5/10}%. (Requires Vampiric Embrace; "
          "same-tier arrow in WoW, not expressible as 'requires'.)",
          [P_mod("Effect", 25, abilities=pr("vampiric_embrace"))]),
        T(s("darkness"), "Darkness", "shadow", 6, 2, 5,
          "Increases your Shadow spell damage by {2/4/6/8/10}%.", [P_stat("DamageDone", 2, pct=True, school="Shadow")]),
        T(s("shadowform"), "Shadowform", "void", 7, 1, 1,
          "Assume a Shadowform, increasing your Shadow damage by 15% and reducing Physical damage done to you by 15%. "
          "However, you may not cast Holy spells while in this form.", [P_grant("priest_shadowform")],
          requires=s("vampiric_embrace")),
    ],
}

TREES = [DISC, HOLY, SHADOW]

# ------------------------------------------------- auras applied by talents
AURAS.append(make_aura("priest_focused_casting", "Focused Casting", "hands_pray", "Buff", "Holy",
                       "Casting is not delayed by damage; increased resistance to Interrupt effects.", 6,
                       special="PriestFocusedCasting"))
AURAS.append(make_aura("priest_inspiration", "Inspiration", "armor", "Buff", "Holy", "Armor increased.", 15,
                       mods=[M("Armor", values=[8, 16, 25], pct=True)]))
AURAS.append(make_aura("priest_blessed_recovery", "Blessed Recovery", "heal_plus", "Buff", "Holy",
                       "Healing a portion of a critical hit taken over 6 sec.", 6, tickInterval=2,
                       tickEffects=[E("Heal", target="Target", special="PriestBlessedRecovery")]))
AURAS.append(make_aura("priest_spirit_tap", "Spirit Tap", "soul_shard", "Buff", "Shadow",
                       "Spirit increased by 100%; 50% of mana regeneration continues while casting.", 15,
                       mods=[M("Spirit", 100, pct=True), M("SpiritRegenWhileCasting", 50)]))
AURAS.append(make_aura("priest_blackout", "Blackout", "shadow", "Debuff", "Shadow", "Stunned.", 3, dispel="Magic",
                       states=["Stun"], tags=["Stun"]))
AURAS.append(make_aura("priest_shadow_vulnerability", "Shadow Vulnerability", "void", "Debuff", "Shadow",
                       "Shadow damage taken increased by 3% per stack.", 15, maxStacks=5,
                       mods=[M("DamageTaken", 3, pct=True, school="Shadow")]))

# Shadow levelling build (Wand Specialization first, then Shadow to Shadowform, then Discipline).
DEFAULT_BUILD = (
    [d("wand_specialization")] * 5
    + [s("spirit_tap")] * 5 + [s("improved_shadow_word_pain")] * 2 + [s("shadow_focus")] * 3 + [s("mind_flay")]
    + [s("improved_mind_blast")] * 5 + [s("shadow_weaving")] * 4 + [s("vampiric_embrace")]
    + [s("improved_psychic_scream")] * 2 + [s("silence")] + [s("shadow_weaving")]
    + [s("darkness")] * 5 + [s("shadowform")]
    + [d("improved_power_word_shield")] * 3 + [d("improved_power_word_fortitude")] * 2 + [d("meditation")] * 3
    + [d("inner_focus")] + [d("unbreakable_will")] + [d("mental_agility")] * 5
)
assert len(DEFAULT_BUILD) == 51, len(DEFAULT_BUILD)
