"""Generates the lv builder's data (Docs/Expansion.md §8 row lv; prefixes lv2 and dg1):

* D/content/map_lanternvale.json — the original village strip (y 0-15, kept exactly as base_map_lanternvale.json holds
  it) plus the northern band of the deepened map (gen_map_lv.py);
* D/content/dgn_root_hollows.json — the Root Hollows map (gen_dungeon.py);
* D/content/lv2_content.json and dgn_root_hollows_content.json — creatures, abilities, auras, loot, items, NPCs,
  dialogues and quests (gen_content.py; item budgets in items_lib.py).

The village dialogues (Elder Maru, Nell, Tobben) gained their lv2/dg1 nodes by hand in dialogues_village.json.
xp_tally.py totals the XP of the new content. Run: python3 Tools/datagen/lv2/gen_lv2.py (rewrites the four files)."""
import json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import jsonfmt
import gen_map_lv
import gen_dungeon
import gen_content

ROOT = os.path.normpath(os.path.join(HERE, "..", "..", "..", "Assets", "Lanternvale", "Resources", "Data", "content"))


def main():
    base = json.load(open(os.path.join(HERE, "base_map_lanternvale.json")))["maps"][0]
    lv = gen_map_lv.lanternvale(base)
    jsonfmt.write(os.path.join(ROOT, "map_lanternvale.json"), {"maps": [lv]})
    jsonfmt.write(os.path.join(ROOT, "dgn_root_hollows.json"), {
        "_note": "The Root Hollows (Docs/Expansion.md §1, §8 row lv): the hidden cave under Old Kusu. Map only; its creatures, loot, items, NPC, dialogue and quest are in dgn_root_hollows_content.json. Generated by Tools/datagen/lv2/gen_lv2.py.",
        "maps": [gen_dungeon.root_hollows()]})
    gen_content.write_all(ROOT, jsonfmt)


if __name__ == "__main__":
    main()
