// Raid loot content (Docs/Expansion.md §8 "Raid loot design", builder raidloot; data in D/content/raid_loot*.json,
// generated by Tools/datagen/raid_loot/gen_raid_loot.py): every class has a complete tier-1 (Hollow Heart) and tier-2
// (Ashwyrm's Roost) set wearable at the raid's level; every set bonus (stats, AbilityMods on real known abilities/tags,
// procs) applies on a level-appropriate unit at exactly its piece count; each boss table rolled for a 10-member mixed
// raid gives 2 set pieces of the boss's slot(s) usable by the party, 2 boss epics, a Rare and gold, and never a
// legendary the party owns; trash tables; and the gear budget (stats, DPS, armour, the authored-budget guardrail).
using System;
using System.Collections.Generic;
using System.Linq;
using Lanternvale.Data;
using Lanternvale.Rules;
using Lanternvale.Util;
using static Lanternvale.Tests.Harness;

namespace Lanternvale.Tests
{
    public static class TestsContentRaidLoot
    {
        static readonly ClassId[] Classes =
            { ClassId.Warrior, ClassId.Paladin, ClassId.Hunter, ClassId.Rogue, ClassId.Priest, ClassId.Shaman, ClassId.Mage, ClassId.Warlock };

        static readonly EquipType[] SetSlots = { EquipType.Head, EquipType.Shoulder, EquipType.Chest, EquipType.Hands, EquipType.Legs };

        sealed class Tier
        {
            public string Prefix;
            public int Req, IlvlMin, IlvlMax;
            public (string Boss, EquipType[] Slots)[] Bosses;
            public string[] Legendaries;
        }

        static readonly Tier[] Tiers =
        {
            new Tier
            {
                Prefix = "r1", Req = 20, IlvlMin = 26, IlvlMax = 28,
                Bosses = new[]
                {
                    ("thornmaw", new[] { EquipType.Hands }), ("twins", new[] { EquipType.Shoulder }),
                    ("mother_mire", new[] { EquipType.Legs }), ("hollow_heart", new[] { EquipType.Head, EquipType.Chest }),
                },
                Legendaries = new[] { "r1_lg_kindlewood", "r1_lg_solace" },
            },
            new Tier
            {
                Prefix = "r2", Req = 30, IlvlMin = 36, IlvlMax = 38,
                Bosses = new[]
                {
                    ("frostclaw", new[] { EquipType.Hands }), ("cinder_drakes", new[] { EquipType.Shoulder }),
                    ("varkas", new[] { EquipType.Legs }), ("vyrmathra", new[] { EquipType.Head, EquipType.Chest }),
                },
                Legendaries = new[] { "r2_lg_embersong", "r2_lg_dawnstring", "r2_lg_last_scale" },
            },
        };

        /// <summary>The armour a class wears below level 40 (Expansion.md §8: Warrior/Paladin Mail, Hunter/Shaman Leather).</summary>
        static ArmorType ArmorFor(ClassId c)
        {
            switch (c)
            {
                case ClassId.Warrior: case ClassId.Paladin: return ArmorType.Mail;
                case ClassId.Hunter: case ClassId.Shaman: case ClassId.Rogue: return ArmorType.Leather;
                default: return ArmorType.Cloth;
            }
        }

        static string SetId(Tier t, ClassId c) => "set_" + t.Prefix + "_" + c.ToString().ToLowerInvariant();

        static bool IsRaidGear(ItemDef d) =>
            d.id.StartsWith("r1_set_", StringComparison.Ordinal) || d.id.StartsWith("r2_set_", StringComparison.Ordinal) ||
            d.id.StartsWith("r1_ep_", StringComparison.Ordinal) || d.id.StartsWith("r2_ep_", StringComparison.Ordinal) ||
            d.id.StartsWith("r1_lg_", StringComparison.Ordinal) || d.id.StartsWith("r2_lg_", StringComparison.Ordinal);

        static Unit Character(ClassId cls, int level, string name = null)
        {
            var u = UnitFactory.CreateCharacter(Db, cls, name ?? cls.ToString(), level, learnAll: true);
            Progression.AutoAllocateTalents(u);
            Progression.LearnAllAvailable(u);
            UnitFactory.AttachPassives(u);
            u.InvalidateStats();
            u.RestoreFull();
            return u;
        }

        static void Wear(Unit u, ItemDef def)
        {
            var s = EquipmentRules.ChooseSlot(u, def);
            Assert(s.HasValue && EquipmentRules.CannotEquipReason(u, def, s.Value) == null,
                $"{u.Name} (level {u.Level}) can wear {def.id}: {(s.HasValue ? EquipmentRules.CannotEquipReason(u, def, s.Value) : EquipmentRules.CannotUseReason(u, def) ?? "no slot")}");
            EquipmentRules.Equip(u, new ItemInstance(def), s.Value);
        }

        static ItemDef[] SetItems(Tier t, ClassId c)
        {
            var set = Db.ItemSet(SetId(t, c));
            Assert(set != null, "set " + SetId(t, c));
            return set.items.Select(id => Db.Item(id)).ToArray();
        }

        // ------------------------------------------------------------------ sets: complete and wearable

        [Test]
        public static void TierSets_EveryClassHasACompleteWearableSet()
        {
            foreach (var t in Tiers)
                foreach (var cls in Classes)
                {
                    var set = Db.ItemSet(SetId(t, cls));
                    Assert(set != null && !string.IsNullOrEmpty(set.name), $"{t.Prefix}: {cls} has a set");
                    var items = SetItems(t, cls);
                    Assert(items.Length == 5 && items.All(d => d != null), $"{set.id}: 5 pieces");
                    Assert(items.Select(d => d.equip).OrderBy(e => e).SequenceEqual(SetSlots.OrderBy(e => e)),
                        $"{set.id}: head, shoulders, chest, hands and legs ({string.Join(",", items.Select(d => d.equip))})");
                    foreach (var d in items)
                    {
                        Assert(d.quality == Quality.Epic, d.id + " is Epic");
                        Assert(d.requiredLevel == t.Req, $"{d.id} requires level {t.Req}");
                        Assert(d.itemLevel >= t.IlvlMin && d.itemLevel <= t.IlvlMax, $"{d.id} item level {d.itemLevel} in {t.IlvlMin}-{t.IlvlMax}");
                        Assert(d.classes.Length == 1 && d.classes[0] == cls, $"{d.id} is {cls}-only");
                        Assert(d.armorType == ArmorFor(cls), $"{d.id} is {ArmorFor(cls)} ({d.armorType})");
                        Assert(d.stats.Count >= 3 && !string.IsNullOrEmpty(d.description) && !string.IsNullOrEmpty(d.name), d.id + " has stats, a name and flavour");
                        Assert(Db.SetOf(d.id) == set, d.id + " belongs to its set");
                    }
                    Assert(set.bonuses.Select(b => b.pieces).SequenceEqual(new[] { 2, 4, 5 }), $"{set.id}: bonuses at 2, 4 and 5 pieces");
                    foreach (var b in set.bonuses)
                        Assert(!string.IsNullOrEmpty(b.description) && (b.stats.Count > 0 || b.equipEffects.Count > 0), $"{set.id} ({b.pieces}): an effect and its text");

                    // the class wears all five at the raid's level; one level lower it cannot, nor can another class
                    var u = Character(cls, t.Req);
                    foreach (var d in items) Wear(u, d);
                    Assert(ItemSets.Active(u).Count == 3 && ItemSets.Progress(u, set).Equipped == 5, $"{set.id}: 5 pieces worn, 3 bonuses active");
                    var young = Character(cls, t.Req - 1);
                    Assert(EquipmentRules.CannotUseReason(young, items[0]) != null, $"{set.id}: not before level {t.Req}");
                    var other = Classes[(Array.IndexOf(Classes, cls) + 1) % Classes.Length];
                    Assert(!LootContext.CanUse(Character(other, t.Req), items[0]), $"{set.id}: a {other} cannot use it");
                }
        }

        // ------------------------------------------------------------------ sets: every bonus applies

        static float StatValue(Unit u, StatId s, School? school)
        {
            var b = u.Stats.Block;
            return StatBlock.CombineOf(s) == StatCombine.Multiplicative ? b.Mult(s, school) : b.Flat(s, school);
        }

        static float ModValue(AbilityModSet m, AbilityProperty p)
        {
            switch (p)
            {
                case AbilityProperty.Damage: return m.DamagePct;
                case AbilityProperty.Healing: return m.HealingPct;
                case AbilityProperty.Effect: return m.EffectPct;
                case AbilityProperty.CritChance: return m.CritChance;
                case AbilityProperty.CritBonus: return m.CritBonusPct;
                case AbilityProperty.Cost: return m.CostPct;
                case AbilityProperty.CostFlat: return m.CostFlat;
                case AbilityProperty.Cooldown: return m.Cooldown;
                case AbilityProperty.CastTime: return m.CastTime;
                case AbilityProperty.Range: return m.RangePct;
                case AbilityProperty.Radius: return m.RadiusPct;
                case AbilityProperty.Duration: return m.Duration;
                case AbilityProperty.DurationPct: return m.DurationPct;
                case AbilityProperty.Threat: return m.ThreatPct;
                case AbilityProperty.HitChance: return m.HitChance;
                case AbilityProperty.Charges: return m.Charges;
                case AbilityProperty.ComboPoints: return m.ComboPoints;
                default: return m.Gcd;
            }
        }

        /// <summary>The unit's own class abilities (known, not passive) a filter selects.</summary>
        static List<AbilityDef> KnownMatching(Unit u, PassiveDef p) =>
            u.Abilities.Keys.Select(id => Db.Ability(id))
                .Where(a => a != null && a.classId == u.ClassId && !a.passive && AbilityMods.Matches(p, a))
                .OrderBy(a => a.id, StringComparer.Ordinal).ToList();

        /// <summary>Filters name real abilities of the set's class (trainable by the raid's level, not talent-only) or tags/schools they carry.</summary>
        static void AssertFiltersReal(Unit u, string where, string[] abilities, string[] tags, School[] schools)
        {
            foreach (var id in abilities)
            {
                var a = Db.Ability(id);
                Assert(a != null, $"{where}: ability '{id}' exists");
                Assert(a.classId == u.ClassId && !a.fromTalent && a.learnLevel <= u.Level && u.Knows(id),
                    $"{where}: '{id}' is a {u.ClassId} ability known at level {u.Level}");
            }
            var own = u.Abilities.Keys.Select(id => Db.Ability(id)).Where(a => a != null && a.classId == u.ClassId && !a.passive).ToList();
            foreach (var tag in tags)
                Assert(own.Any(a => AbilityMods.HasTag(a, tag)), $"{where}: tag '{tag}' is on a known {u.ClassId} ability");
            foreach (var s in schools)
                Assert(own.Any(a => a.school == s), $"{where}: school {s} has a known {u.ClassId} ability");
        }

        static Battle NewBattle(int seed) => new Battle(Db, new Rng((ulong)seed), new StraightLinePathfinder(80f, 60f), new Inventory(), true);

        /// <summary>A unit of the set's class wearing the set's first <paramref name="pieces"/> pieces.</summary>
        static Unit Wearing(Tier t, ClassId cls, int pieces)
        {
            var u = Character(cls, t.Req);
            foreach (var d in SetItems(t, cls).Take(pieces)) Wear(u, d);
            return u;
        }

        /// <summary>What a proc's spell damage can come to (hit, or a miss / resist / absorb of it).</summary>
        static readonly CombatEventType[] SpellOutcomes =
            { CombatEventType.Damage, CombatEventType.Miss, CombatEventType.Resist, CombatEventType.Absorb, CombatEventType.Immune };

        static readonly ProcTrigger[] HealTriggers = { ProcTrigger.OnHealCast };

        /// <summary>
        /// Fires <paramref name="trigger"/> on the unit up to <paramref name="tries"/> times (chance procs) and returns
        /// the battle once the proc's cooldown key is set, or null if it never fired.
        /// </summary>
        static Battle FireUntil(Unit u, ProcDef proc, string key, int tries, int seed, out Unit other)
        {
            var b = NewBattle(seed);
            u.Position = new Vec2(20f, 20f);
            var foe = UnitFactory.CreateCreature(Db, Db.Creature("cr_wolf"), u.Level, Team.Enemy);
            foe.Position = new Vec2(21.5f, 20f);
            foe.MaxHealthMult = 200f; foe.InvalidateStats(); foe.Health = foe.MaxHealth;
            b.AddUnit(u); b.AddUnit(foe);
            b.Begin();
            u.Health = u.MaxHealth * 0.5f;   // room for heals
            other = Array.IndexOf(HealTriggers, proc.trigger) >= 0 ? u : foe;
            // the triggering ability: one the proc's filters accept (or a fitting one of the class)
            AbilityDef ability = null;
            var probe = new PassiveDef { abilities = proc.abilities, tags = proc.tags, schools = proc.schools };
            var known = KnownMatching(u, probe);
            if (proc.trigger == ProcTrigger.OnHealCast) known = known.Where(a => AbilityMods.HasTag(a, "Heal")).ToList();
            if (proc.trigger == ProcTrigger.OnFinisher) known = known.Where(a => AbilityMods.HasTag(a, "Finisher")).ToList();
            if (known.Count > 0) ability = known[0];
            var info = new ProcInfo
            {
                Ability = ability, School = ability?.school ?? School.Physical, Ranged = proc.trigger == ProcTrigger.OnRangedHit,
                Crit = proc.trigger == ProcTrigger.OnSpellCrit || proc.trigger == ProcTrigger.OnMeleeCrit || proc.trigger == ProcTrigger.OnCrit,
                Periodic = proc.trigger == ProcTrigger.OnPeriodicDamage, Damage = 50f, WeaponSpeed = 2.5f, ComboPoints = 3,
            };
            for (int i = 0; i < tries; i++)
            {
                b.FireProcs(proc.trigger, u, other, info);
                if (u.ProcCooldowns.TryGetValue(key, out var cd) && cd > 0) return b;
            }
            return null;
        }

        [Test]
        public static void TierSets_EveryBonusAppliesAtItsPieceCount()
        {
            int checkedMods = 0, checkedStats = 0, checkedProcs = 0;
            foreach (var t in Tiers)
                foreach (var cls in Classes)
                {
                    var set = Db.ItemSet(SetId(t, cls));
                    var items = SetItems(t, cls);
                    var u = Character(cls, t.Req);
                    int worn = 0;
                    for (int bi = 0; bi < set.bonuses.Count; bi++)
                    {
                        var bonus = set.bonuses[bi];
                        string where = $"{set.id} ({bonus.pieces})";
                        while (worn < bonus.pieces - 1) Wear(u, items[worn++]);
                        Assert(!ItemSets.Active(u).Any(a => a.Bonus == bonus), where + ": inactive one piece short");

                        // snapshot before the last piece
                        var statKeys = bonus.stats.Select(m => (m.stat, m.school, m.value, m.pct))
                            .Concat(bonus.equipEffects.Where(p => p.type == "Stat").Select(p => (p.stat, p.school, p.value, p.pct))).ToList();
                        var before = statKeys.Select(k => StatValue(u, k.stat, k.school)).ToList();
                        var mods = bonus.equipEffects.Where(p => p.type == "AbilityMod").ToList();
                        var modTargets = new List<(PassiveDef p, AbilityDef a, float before)>();
                        foreach (var p in mods)
                        {
                            AssertFiltersReal(u, where, p.abilities, p.tags, p.schools);
                            var known = KnownMatching(u, p);
                            Assert(known.Count > 0, where + $": the {p.property} mod selects a known ability");
                            foreach (var a in known) modTargets.Add((p, a, ModValue(AbilityMods.For(u, a), p.property)));
                        }

                        var piece = items[worn++];
                        Wear(u, piece);
                        Assert(ItemSets.Active(u).Any(a => a.Bonus == bonus), where + ": active at its piece count");

                        // stats: the bonus plus the new piece's own stats
                        for (int i = 0; i < statKeys.Count; i++)
                        {
                            var k = statKeys[i];
                            Assert(!k.pct || StatBlock.CombineOf(k.stat) != StatCombine.Base, where + ": no pct on base stats");
                            float now = StatValue(u, k.stat, k.school);
                            if (StatBlock.CombineOf(k.stat) == StatCombine.Multiplicative)
                                AssertNear(now / before[i], 1f + statKeys.Where(x => x.stat == k.stat && x.school == k.school).Sum(x => x.value) / 100f, 1e-3f, $"{where}: {k.stat} ×");
                            else
                            {
                                float fromPiece = piece.stats.Where(m => m.stat == k.stat && (m.school == null || m.school == k.school)).Sum(m => m.value);
                                float fromBonus = statKeys.Where(x => x.stat == k.stat && x.school == k.school).Sum(x => x.value);
                                AssertNear(now - before[i], fromBonus + fromPiece, 1e-3f, $"{where}: {k.stat} +");
                            }
                            checkedStats++;
                        }
                        // ability mods: every selected known ability moves by the bonus's mods of that property
                        foreach (var (p, a, b0) in modTargets)
                        {
                            float expect = mods.Where(q => q.property == p.property && AbilityMods.Matches(q, a)).Sum(q => q.value);
                            AssertNear(ModValue(AbilityMods.For(u, a), p.property) - b0, expect, 1e-3f, $"{where}: {p.property} of {a.id}");
                            checkedMods++;
                        }
                        // procs: fire at the piece count (cooldown key set, effect seen), never one piece short
                        for (int ei = 0; ei < bonus.equipEffects.Count; ei++)
                        {
                            var p = bonus.equipEffects[ei];
                            if (p.type == "Special") Assert(!string.IsNullOrEmpty(p.special), where + ": named special");
                            if (p.type != "Proc") continue;
                            Assert(p.proc != null && p.proc.internalCooldown > 0 && (p.proc.chance > 0 || p.proc.ppm > 0), where + ": a chance proc with a cooldown");
                            AssertFiltersReal(u, where + " proc", p.proc.abilities, p.proc.tags, p.proc.schools);
                            string key = "s:" + set.id + ":" + bi + ":" + ei;

                            var full = Wearing(t, cls, bonus.pieces);
                            Assert(ItemSets.Active(full).Any(a => a.Bonus == bonus && ItemSets.ProcKey(a, ei) == key), where + ": proc key " + key);
                            var b = FireUntil(full, p.proc, key, 4000, 11 + bi, out var other);
                            Assert(b != null, $"{where}: the {p.proc.trigger} proc fires");
                            foreach (var e in p.proc.effects)
                            {
                                if (e.type == EffectType.ApplyAura)
                                {
                                    var on = e.target == EffectTarget.Self ? full : other;
                                    Assert(on.Auras.Any(x => x.Def.id == e.aura), $"{where}: {e.aura} applied");
                                }
                                else if (e.type == EffectType.Damage || e.type == EffectType.Heal)
                                    Assert(b.Events.Any(x => x.Source == full && (e.type == EffectType.Heal ? x.Type == CombatEventType.Heal : Array.IndexOf(SpellOutcomes, x.Type) >= 0)),
                                        $"{where}: the proc's {e.type} lands");
                            }
                            var shy = Wearing(t, cls, bonus.pieces - 1);
                            Assert(FireUntil(shy, p.proc, key, 300, 7, out _) == null, where + ": no proc one piece short");
                            checkedProcs++;
                        }
                    }
                }
            Assert(checkedMods >= 16 && checkedStats >= 5 && checkedProcs == 16, $"checked {checkedMods} mods, {checkedStats} stats, {checkedProcs} procs");
        }

        // ------------------------------------------------------------------ boss tables

        static readonly ClassId[] MixedRaid =
        {
            ClassId.Warrior, ClassId.Paladin, ClassId.Priest, ClassId.Shaman, ClassId.Hunter,
            ClassId.Rogue, ClassId.Mage, ClassId.Warlock, ClassId.Warrior, ClassId.Priest,
        };

        static List<Unit> Raid(int level, ClassId[] classes) => classes.Select((c, i) => Character(c, level, c + "_" + i)).ToList();

        static bool IsSetPiece(ItemDef d, Tier t) => d.id.StartsWith(t.Prefix + "_set_", StringComparison.Ordinal);
        static bool IsBossEpic(ItemDef d, Tier t) => d.id.StartsWith(t.Prefix + "_ep_", StringComparison.Ordinal);

        [Test]
        public static void BossTables_TenRaidGetsTwoSetPiecesPerSlotUsableByTheParty()
        {
            foreach (var t in Tiers)
            {
                var raid = Raid(t.Req, MixedRaid);
                for (int bi = 0; bi < t.Bosses.Length; bi++)
                {
                    var (boss, slots) = t.Bosses[bi];
                    string tid = "lt_" + t.Prefix + "_" + boss;
                    Assert(Db.LootTables.TryGetValue(tid, out var table), "table " + tid);
                    Assert(table.goldMin > 0 && table.goldMax >= table.goldMin, tid + ": gold");
                    bool final = bi == t.Bosses.Length - 1;

                    // structure: per slot a pool of the 8 classes' pieces, the epic pool, a Rare random, legendaries on the final
                    foreach (var slot in slots)
                    {
                        var expect = Classes.Select(c => SetItems(t, c).Single(d => d.equip == slot).id).OrderBy(x => x).ToList();
                        Assert(table.entries.Any(e => e.pool.OrderBy(x => x).SequenceEqual(expect) && e.perMembers == 5 && e.partyUsable && e.chance >= 100 && !e.skipOwned),
                            $"{tid}: a {slot} set pool, perMembers 5, partyUsable");
                    }
                    Assert(table.entries.Count(e => e.pool.Length > 0 && e.pool.All(id => IsSetPiece(Db.Item(id), t))) == slots.Length, tid + ": only its slots' set pools");
                    var epicEntry = table.entries.Single(e => e.pool.Length > 1 && e.pool.All(id => IsBossEpic(Db.Item(id), t)));
                    Assert(epicEntry.perMembers == 5 && epicEntry.partyUsable && epicEntry.chance >= 100 && epicEntry.pool.Length >= 4, tid + ": the epic pool");
                    Assert(table.entries.Any(e => e.random && e.quality == Quality.Rare && e.chance >= 100), tid + ": a Rare random");
                    var lgEntries = table.entries.Where(e => e.pool.Any(id => Db.Item(id).quality == Quality.Legendary)).ToList();
                    if (final)
                    {
                        Assert(lgEntries.SelectMany(e => e.pool).OrderBy(x => x).SequenceEqual(t.Legendaries.OrderBy(x => x)), tid + ": the raid's legendaries");
                        Assert(lgEntries.All(e => e.skipOwned && e.chance >= 4 && e.chance <= 6 && e.pool.Length == 1), tid + ": legendaries skipOwned at 4-6%");
                    }
                    else Assert(lgEntries.Count == 0, tid + ": no legendary before the final boss");

                    // rolls for a 10-member mixed raid
                    for (int seed = 1; seed <= 40; seed++)
                    {
                        var ctx = LootContext.For(raid, new Inventory());
                        Assert(ctx.Members == 10, "10 members");
                        var drop = LootGenerator.Roll(Db, tid, t.Req + 2, new Rng((ulong)(seed * 101 + bi)), ctx);
                        var defs = drop.Items.Select(i => i.Def).ToList();
                        foreach (var slot in slots)
                        {
                            var pieces = defs.Where(d => IsSetPiece(d, t) && d.equip == slot).ToList();
                            Assert(pieces.Count == 2 && pieces[0].id != pieces[1].id, $"{tid} seed {seed}: 2 different {slot} pieces ({string.Join(",", pieces.Select(d => d.id))})");
                            foreach (var d in pieces)
                                Assert(raid.Any(m => LootContext.CanUse(m, d) && Array.IndexOf(d.classes, m.ClassId) >= 0), $"{tid}: {d.id} fits someone in the raid");
                        }
                        Assert(defs.Count(d => IsSetPiece(d, t)) == 2 * slots.Length, $"{tid}: no other set pieces");
                        var epics = defs.Where(d => IsBossEpic(d, t)).ToList();
                        Assert(epics.Count == 2 && epics[0].id != epics[1].id && epics.All(d => raid.Any(m => LootContext.CanUse(m, d))), $"{tid}: 2 different usable epics");
                        Assert(defs.Count(d => d.quality == Quality.Legendary) == defs.Where(d => d.quality == Quality.Legendary).Select(d => d.id).Distinct().Count(), tid + ": no legendary twice");
                        Assert(defs.Any(d => d.quality == Quality.Rare) && drop.Gold >= table.goldMin, tid + ": a Rare and gold");
                    }
                }

                // a raid of one class gets that class's pieces only (both rolls)
                var mages = Raid(t.Req, Enumerable.Repeat(ClassId.Mage, 10).ToArray());
                var hands = LootGenerator.Roll(Db, "lt_" + t.Prefix + "_" + t.Bosses[0].Boss, t.Req, new Rng(5), LootContext.For(mages, new Inventory()))
                    .Items.Select(i => i.Def).Where(d => IsSetPiece(d, t)).ToList();
                Assert(hands.Count == 2 && hands.All(d => d.classes.Single() == ClassId.Mage), "an all-mage raid: two mage pieces");
            }
        }

        [Test]
        public static void FinalBosses_LegendariesDropRarelyAndNeverWhenOwned()
        {
            foreach (var t in Tiers)
            {
                var raid = Raid(t.Req, MixedRaid);
                string tid = "lt_" + t.Prefix + "_" + t.Bosses[t.Bosses.Length - 1].Boss;
                var counts = t.Legendaries.ToDictionary(id => id, id => 0);
                const int N = 1500;
                for (int seed = 1; seed <= N; seed++)
                {
                    var drop = LootGenerator.Roll(Db, tid, t.Req + 3, new Rng((ulong)seed), LootContext.For(raid, new Inventory()));
                    foreach (var i in drop.Items) if (counts.ContainsKey(i.Id)) counts[i.Id]++;
                }
                foreach (var kv in counts)
                    Assert(kv.Value >= N * 0.02 && kv.Value <= N * 0.09, $"{kv.Key}: {kv.Value} of {N} kills (about 5%)");

                // owned (bags or worn by anyone): never again
                foreach (var lg in t.Legendaries)
                {
                    var bags = new Inventory();
                    bags.Add(Db.Item(lg));
                    var worn = Raid(t.Req, MixedRaid);
                    var def = Db.Item(lg);
                    var wearer = worn.First(m => LootContext.CanUse(m, def));
                    EquipmentRules.Equip(wearer, new ItemInstance(def), EquipmentRules.ChooseSlot(wearer, def).Value);
                    for (int seed = 1; seed <= 400; seed++)
                    {
                        Assert(!LootGenerator.Roll(Db, tid, t.Req, new Rng((ulong)seed), LootContext.For(raid, bags)).Items.Any(i => i.Id == lg), $"{lg} in the bags: no second copy");
                        Assert(!LootGenerator.Roll(Db, tid, t.Req, new Rng((ulong)seed), LootContext.For(worn, new Inventory())).Items.Any(i => i.Id == lg), $"{lg} worn: no second copy");
                    }
                }
            }
        }

        [Test]
        public static void TrashTables_RareRandomsAndASmallEpicChance()
        {
            foreach (var t in Tiers)
            {
                string tid = "lt_" + t.Prefix + "_trash";
                Assert(Db.LootTables.TryGetValue(tid, out var table) && table.goldMax > 0, tid);
                Assert(table.entries.Any(e => e.random && e.quality == Quality.Rare && e.chance > 0), tid + ": a Rare random");
                var epic = table.entries.Single(e => e.pool.Length > 0);
                Assert(epic.chance > 0 && epic.chance <= 5 && epic.pool.All(id => IsBossEpic(Db.Item(id), t)) && epic.partyUsable, tid + ": a small raid-epic chance");
                Assert(!table.entries.Any(e => e.pool.Any(id => Db.Item(id).quality == Quality.Legendary || IsSetPiece(Db.Item(id), t))), tid + ": no set pieces or legendaries");
                var raid = Raid(t.Req, MixedRaid);
                int rares = 0, epics = 0;
                for (int seed = 1; seed <= 400; seed++)
                    foreach (var i in LootGenerator.Roll(Db, tid, t.Req + 1, new Rng((ulong)seed), LootContext.For(raid, new Inventory())).Items)
                    {
                        if (i.Def.quality == Quality.Rare) rares++;
                        if (i.Def.quality == Quality.Epic) epics++;
                    }
                Assert(rares >= 20 && epics >= 1 && epics <= 25, $"{tid}: {rares} Rares and {epics} epics in 400 kills");
            }
        }

        // ------------------------------------------------------------------ budget

        [Test]
        public static void RaidGear_FollowsTheGearBudget()
        {
            var gear = Db.Items.Values.Where(IsRaidGear).OrderBy(d => d.id, StringComparer.Ordinal).ToList();
            int sets = gear.Count(d => d.id.Contains("_set_")), eps = gear.Count(d => d.id.Contains("_ep_")), lgn = gear.Count(d => d.id.Contains("_lg_"));
            Assert(sets == 80 && lgn == 5 && eps >= 24, $"80 set pieces ({sets}), 24+ raid epics ({eps}), 5 legendaries ({lgn})");
            foreach (var d in gear)
            {
                bool lg = d.id.Contains("_lg_");
                bool r1 = d.id.StartsWith("r1_", StringComparison.Ordinal);
                Assert(d.quality == (lg ? Quality.Legendary : Quality.Epic), d.id + ": quality");
                Assert(d.requiredLevel == (r1 ? 20 : 30), d.id + ": required level");
                if (lg) Assert(d.unique && d.equipEffects.Any(p => p.type == "Proc" && !string.IsNullOrEmpty(p.description)), d.id + ": unique with a described proc");
                else Assert(d.itemLevel >= (r1 ? 26 : 36) && d.itemLevel <= (r1 ? 28 : 38), d.id + ": item level");
                Assert(!string.IsNullOrEmpty(d.description) && d.price > 0 && string.IsNullOrEmpty(d.use), d.id + ": flavour, price, no use");
                foreach (var p in d.equipEffects) if (p.type == "Proc") Assert(p.proc.internalCooldown > 0, d.id + ": item procs have a cooldown");

                // stats: 0.55 × ilvl × Qa × slot (Qa Epic 2.1, Legendary 2.8), costed like ItemGenerator
                float qa = lg ? 2.8f : 2.1f;
                float target = ItemGenerator.StatBudget(d.itemLevel, d.quality, d.equip) / ItemGenerator.QualityMult(d.quality) * qa;
                float cost = d.stats.Sum(m => m.value * Cost(m.stat)) + d.equipEffects.Where(p => p.type == "Stat").Sum(p => p.value * Cost(p.stat));
                Assert(cost >= target * 0.88f && cost <= target * 1.12f, $"{d.id}: stats cost {cost:0.#} vs authored budget {target:0.#}");
                // armour and weapon DPS
                if (d.armorType != ArmorType.None && d.weaponType == WeaponType.None)
                    AssertNear(d.armor, ItemGenerator.ArmorValue(d.armorType, d.equip, d.itemLevel, d.quality), 1f, d.id + ": ArmorValue");
                if (d.weaponType != WeaponType.None && d.weaponType != WeaponType.Shield && d.weaponType != WeaponType.HeldInOffhand)
                {
                    float dps = (d.minDamage + d.maxDamage) * 0.5f / d.speed;
                    float ratio = dps / ItemGenerator.WeaponDps(d.weaponType, d.itemLevel, d.quality);
                    float want = lg ? 0.95f : 0.86f;
                    Assert(Math.Abs(ratio - want) < 0.03f, $"{d.id}: DPS {dps:0.0} = {ratio:0.00} × WeaponDps (want {want})");
                }
                if (d.weaponType == WeaponType.Shield) Assert(d.armor > 0 && d.block > 0, d.id + ": shield armour and block");
            }

            // every weapon type the classes use drops somewhere in the raids (shields and held off-hands included)
            var used = new HashSet<WeaponType>(Db.Classes.Values.SelectMany(c => c.weaponTypes)) { WeaponType.Shield, WeaponType.HeldInOffhand };
            var dropped = new HashSet<WeaponType>(gear.Where(d => !IsSetPieceAny(d)).Select(d => d.weaponType));
            Assert(used.All(dropped.Contains), "weapon types without a raid drop: " + string.Join(", ", used.Where(w => !dropped.Contains(w))));
            foreach (var slot in new[] { EquipType.Trinket, EquipType.Finger, EquipType.Neck, EquipType.Back, EquipType.OffHand })
                foreach (var prefix in new[] { "r1_ep_", "r2_ep_" })
                    Assert(gear.Any(d => d.id.StartsWith(prefix, StringComparison.Ordinal) && d.equip == slot), $"{prefix}*: a {slot} epic");
            var lgs = gear.Where(d => d.quality == Quality.Legendary).ToDictionary(d => d.id, d => d.weaponType);
            Assert(lgs.Count == 5 && lgs["r1_lg_kindlewood"] == WeaponType.Staff && lgs["r1_lg_solace"] == WeaponType.OneHandMace &&
                   lgs["r2_lg_embersong"] == WeaponType.TwoHandSword && lgs["r2_lg_dawnstring"] == WeaponType.Bow && lgs["r2_lg_last_scale"] == WeaponType.Shield,
                "the five legendaries: a caster staff, a healer's mace, a greatsword, a bow and a tank shield");

            // the authored stat-budget guardrail of the items engine holds with the raid gear in
            TestsItemSetsAndLoot.AuthoredStatBudget_WithinBounds();
        }

        static bool IsSetPieceAny(ItemDef d) => Db.SetOf(d.id) != null;

        static float Cost(StatId s)
        {
            switch (s)
            {
                case StatId.AttackPower: case StatId.RangedAttackPower: return 0.5f;
                case StatId.SpellDamage: return 0.86f;
                case StatId.HealingPower: return 0.45f;
                case StatId.MeleeCrit: case StatId.SpellCrit: case StatId.RangedCrit: case StatId.MeleeHit: case StatId.SpellHit: case StatId.Dodge: case StatId.Parry: return 14f;
                case StatId.Armor: return 0.1f;
                case StatId.ManaRegen: case StatId.HealthRegen: return 2.5f;
                default: return 1f;
            }
        }
    }
}
