// 必杀技测试（tests/sim.js (4)(5)(5b)(5c)(6) 的 C# 版）与参考结果比对：
//   (ref) Specials.Of 对 ref/specials-ref.txt 全部 433 行（世界剧本 361 名 + 72 名兜底生成）逐字段与 JS 相同；
//   (4) 数据自检：每位武将都有招式、名称唯一、(机制, 参数) 唯一、兜底生成器确定且不撞车、校验器能发现错误；
//   (5) UseSpecial 随机压力测试（不得出现负兵力 / 重叠 / 越界）与每位武将的参考伤害倍率；
//   (5b) 规则：攻守对称的持续时间、突击不能撞走本城 / 城门守军、范围封顶、各机制单体 / 密集伤害倍率；
//   (5c) 世界剧本武将：全部手写、唯一、参考伤害倍率；
//   (6) Duel() 拆成 DuelAccepts + DuelFinish 后随机数顺序不变。
// 测试代码里与 JS 的 SG.Random.value() 对应处用 Random.NextDouble()（替身专有，双精度），使随机局面与 JS 完全相同。
using System;
using System.Collections.Generic;
using System.Linq;
using Sanguo;
using R = UnityEngine.Random;

class PSp
{
    static int fails;
    static General Dummy(int id, string name, int war, int intel) { return new General { id = id, name = name, war = war, intel = intel, pol = 50, faction = -1, troops = 3500, training = 60, loyalty = 80 }; }
    static BattleSetup Setup(GameState g, City target, List<General> atk, List<General> def, int food)
    {
        return new BattleSetup { attacker = 0, defender = 1, src = g.cities[0], target = target, atk = atk, def = def, atkFood = food, atkGold = 0 };
    }
    static string Dump(Special sp) { return string.Join("|", new[] { sp.gen, sp.name, sp.kind, sp.stat, Specials.Signature(sp), sp.color, sp.fx, sp.cry, sp.desc }); }
    static readonly string[] DamageKinds = { "smite", "cleave", "charge", "rampage", "volley", "blaze", "storm", "flood", "drain" };

    static int Main()
    {
        BattleModel.specialsEnabled = true;   // 同网页版默认（游戏内暂时默认 false，见 BattleModel.specialsEnabled）
        Console.OutputEncoding = new System.Text.UTF8Encoding(false);
        var t0 = DateTime.Now;
        Section("(ref) Specials.Of vs JS reference (ref/specials-ref.txt)", RefCheck);
        Specials.ResetCache();
        Section("(4) specials data", Data);
        Section("(5) useSpecial fuzz + reference damage ratios", Fuzz);
        Section("(5b) specials rules: symmetric durations, castle hold, area cap, per-kind damage", RulesCheck);
        Section("(5c) world scenario generals: hand-made, unique, reference damage ratios", World);
        Section("(6) duel split keeps the random sequence", DuelSplit);
        Console.WriteLine($"total {Sim.F((DateTime.Now - t0).TotalSeconds, 1)}s");
        Console.WriteLine(fails == 0 ? "ALL OK" : "FAILURES: " + fails);
        return fails;
    }
    static void Section(string name, Action a)
    {
        Console.WriteLine("== " + name + " ==");
        try { a(); } catch (Exception e) { fails++; BattleModel.specialsEnabled = true; R.ValueOverride = null; Console.WriteLine(name.Split(' ')[0] + " FAILED: " + e); }
    }

    // ------------------------------------------------------------ 参考结果 --
    static void RefCheck()
    {
        Specials.ResetCache();
        int n = 0, bad = 0, auto = 0;
        foreach (var line in System.IO.File.ReadAllLines("ref/specials-ref.txt"))
        {
            if (line.StartsWith("#") || line.Trim().Length == 0) continue;
            var p = line.Split('\t');
            var sp = Specials.Of(p[0], int.Parse(p[1]), int.Parse(p[2]), int.Parse(p[3]), p[4]);
            Func<string, string> clean = s => (s ?? "").Replace('\t', ' ').Replace('\n', ' ');
            var got = new[] { sp.gen, sp.auto ? "auto" : "hand", sp.name, sp.kind, sp.stat, Specials.Signature(sp), sp.color, sp.fx, sp.cry, sp.desc }.Select(clean).ToArray();
            var want = p.Skip(6).ToArray();
            n++; if (sp.auto) auto++;
            for (int i = 0; i < got.Length; i++)
                if (i >= want.Length || got[i] != want[i])
                {
                    bad++;
                    if (bad <= 6) Console.WriteLine($"  MISMATCH {p[0]} field {i}:\n    got  {got[i]}\n    want {(i < want.Length ? want[i] : "(none)")}");
                    break;
                }
        }
        Console.WriteLine($"{n} generals compared ({auto} generated by the fallback), {bad} mismatches");
        if (bad > 0 || n < 400) throw new Exception("specials differ from the JS reference");
    }

    // ------------------------------------------------------------ (4) 数据 --
    static void Data()
    {
        GameState.Current = null;
        var rep = Specials.Check();
        Console.WriteLine($"generals {rep.total}: hand-made {rep.hand}, generated {rep.auto}; duplicate names {rep.dupNames.Count}, duplicate (kind, params) {rep.dupSigs.Count}, data problems {rep.problems.Count}");
        foreach (var d in rep.dupNames) Console.WriteLine("  dup name " + d.Key + ": " + string.Join(", ", d.Value));
        foreach (var d in rep.dupSigs) Console.WriteLine("  dup params " + d.Key + ": " + string.Join(", ", d.Value));
        foreach (var p in rep.problems) Console.WriteLine("  problem: " + p);
        if (!rep.ok) throw new Exception("specials self-check failed");
        // 剧本中每位武将都有招式，且 kind 合法、desc 非空
        var roster = ScenarioData.Generals.Select(l => { var p = l.Split('|'); return new General { name = p[0], war = int.Parse(p[1]), intel = int.Parse(p[2]), pol = int.Parse(p[3]) }; }).ToList();
        foreach (var g in roster)
        {
            var sp = Specials.Of(g);
            if (sp == null || !Specials.KindExists(sp.kind) || string.IsNullOrEmpty(sp.name) || string.IsNullOrEmpty(sp.desc) || !System.Text.RegularExpressions.Regex.IsMatch(sp.color, "^#[0-9a-f]{6}$") || Array.IndexOf(SpecialsData.FxStyles, sp.fx) < 0)
                throw new Exception("bad special for " + g.name + ": " + Dump(sp));
        }
        // 指定的知名武将使用手写招式
        var want = new Dictionary<string, string> { { "关羽", "青龙偃月斩" }, { "张飞", "长坂怒吼" }, { "赵云", "七进七出" }, { "吕布", "天下无双" }, { "诸葛亮", "借东风" }, { "黄忠", "百步穿杨" }, { "典韦", "双戟护主" }, { "华佗", "麻沸散" }, { "周瑜", "赤壁业火" } };
        foreach (var k in want) if (Specials.Of(k.Key, 0, 0, 0).name != k.Value) throw new Exception(k.Key + " should have " + k.Value);
        // 未经 GameState.Init 的武将 culture 为 null（同网页版的 undefined），文化按南蛮名单回退
        if (new General().culture != null || Specials.CultureOf(new General { name = "孟获" }) != "nanman" || Specials.CultureOf(new General { name = "曹操" }) != "han")
            throw new Exception("General.culture should default to null with the Nanman-list fallback");
        // 兜底生成器：确定性（同名同招）、名称含姓名、与名单内全部招式不撞车
        var synth = new List<General>();
        var cultures = new[] { "han", "wa", "korea", "steppe", "seasia", "tarim", "kushan", "persia", "arab", "roman", "celt", "german", "sarmatian", "nanman", "yi" };
        var rnd = new SeededRandom(4242);
        const string chars = "阿巴卡达伊法加哈米努奥帕萨塔乌瓦克雷图斯马尔罗尼娜莎提亚卑弥呼难升米乙素肖古王区连范师蔓";
        for (int i = 0; i < 160; i++)
        {
            var nm = "";
            int len = 2 + rnd.Next(3);
            for (int j = 0; j < len; j++) nm += chars[rnd.Next(chars.Length)];
            nm += i;
            int war = 20 + rnd.Next(80), intel = 20 + rnd.Next(80), pol = 20 + rnd.Next(80);
            synth.Add(new General { name = nm, war = war, intel = intel, pol = pol, culture = cultures[i % cultures.Length] });
        }
        var a1 = string.Join("\n", synth.Select(g => Dump(Specials.Fallback(g))));
        var a2 = string.Join("\n", synth.Select(g => Dump(Specials.Fallback(g))));
        if (a1 != a2) throw new Exception("fallback generator is not deterministic");
        foreach (var g in synth) if (Specials.Of(g).name.IndexOf(g.name + "·") != 0) throw new Exception("fallback name should start with the general name: " + Specials.Of(g).name);
        var both = roster.Concat(synth).ToList();
        var rep2 = Specials.Check(both);
        if (!rep2.ok) throw new Exception("roster + 160 synthetic world generals: dup names " + rep2.dupNames.Count + ", dup params " + string.Join(" ", rep2.dupSigs.Select(d => string.Join("/", d.Value))) + ", problems " + rep2.problems.Count);
        var kinds = new Dictionary<string, int>();
        foreach (var sp in Specials.All(both)) kinds[sp.kind] = (kinds.ContainsKey(sp.kind) ? kinds[sp.kind] : 0) + 1;
        Console.WriteLine("+160 synthetic world generals: all unique; kinds " + string.Join(" ", kinds.Keys.OrderBy(k => k, StringComparer.Ordinal).Select(k => k + ":" + kinds[k])));
        foreach (var k in Specials.KindKeys) if (!kinds.ContainsKey(k)) throw new Exception("kind never produced: " + k);
        // 校验器能发现常见错误
        var badE = new Specials.Raw { name = "错·招", kind = "smite", color = "red", fx = "nope" };
        badE.Put("power", 9); badE.Put("wat", 1);
        var bad = Specials.Validate(badE, "测试");
        if (bad.Count < 5) throw new Exception("Validate() should report 5+ problems, got " + string.Join("; ", bad));
        Console.WriteLine("specials data OK");
    }

    // ------------------------------------------------------- (5) 压力测试 --
    static void Fuzz()
    {
        R.InitState(777);
        var g = GameState.Current = GameState.NewGame("cao");
        var all = g.generals.ToList();
        var fakeTarget = g.cities[11];
        int used = 0, checkedN = 0;
        var seenKinds = new SortedDictionary<string, int>(StringComparer.Ordinal);
        for (int round = 0; round < 6; round++)
        {
            for (int i = 0; i < all.Count; i += 10)
            {
                var group = all.Skip(i).Take(10).ToList();
                if (group.Count < 2) continue;
                foreach (var x in group) { x.troops = Math.Max(800, x.MaxTroops - R.Range(0, 2500)); x.training = 50 + R.Range(0, 40); }
                int half = (group.Count + 1) / 2;
                var M = new BattleModel(Setup(g, fakeTarget, group.Take(half).ToList(), group.Skip(half).ToList(), 3000));
                // 随机摆到一起（棋盘中部），随机士气 / 混乱 / 已行动
                var spots = new List<UnityEngine.Vector2Int>();
                for (int x = 1; x < 10; x++) for (int y = 1; y < M.H - 1; y++) if (M.Passable(x, y)) spots.Add(new UnityEngine.Vector2Int(x, y));
                for (int k = spots.Count - 1; k > 0; k--) { int j = R.Range(0, k + 1); var t = spots[k]; spots[k] = spots[j]; spots[j] = t; }
                for (int k = 0; k < M.units.Count; k++) { var u = M.units[k]; u.x = spots[k].x; u.y = spots[k].y; u.morale = 20 + R.Range(0, 80); u.acted = R.NextDouble() < 0.4; }
                foreach (var u in M.units.OrderBy(_ => R.NextDouble()).ToList())
                {
                    if (!u.alive || M.result != 0) continue;
                    M.side = u.side;
                    string why;
                    bool ok = M.SpecialUsable(u, out why);
                    var tg = M.SpecialTargets(u);
                    if (u.confused <= 0 && ok != (tg.Count > 0)) throw new Exception("specialUsable disagrees with specialTargets for " + u.gen.name + ": " + why);
                    if (!ok) continue;
                    var tt = tg[R.Range(0, tg.Count)];
                    var plan = M.SpecialPlan(u, tt);
                    double v = M.SpecialValue(u, plan);
                    if (double.IsNaN(v) || double.IsInfinity(v) || v < 0) throw new Exception("bad special value " + v + " for " + u.gen.name);
                    var res = M.UseSpecial(u, tt);
                    used++;
                    seenKinds[res.kind] = (seenKinds.ContainsKey(res.kind) ? seenKinds[res.kind] : 0) + 1;
                    Sim.CheckSpecialResult(res, "fuzz " + u.gen.name);
                    Sim.CheckBattleState(M, "fuzz " + u.gen.name + " " + res.name);
                    if (!u.specialUsed || M.SpecialUsable(u)) throw new Exception("special usable twice: " + u.gen.name);
                    var again = M.UseSpecial(u, tt);
                    if (again.success || again.dmg != 0) throw new Exception("second useSpecial should do nothing");
                    checkedN++;
                }
                // 数日推进：中毒、燃烧、加成到期（EndSide 两次 = 一日）
                for (int d = 0; d < 8 && M.result == 0; d++) { M.EndSide(); Sim.CheckBattleState(M, "fuzz endSide"); }
                if (M.result == 0) foreach (var u in M.units) if (u.alive && u.mods.Any(m => !(m.dot > 0) && m.days > 0 && m.days < 4)) throw new Exception("fuzz: short buff still active after 4 days on " + u.gen.name);
            }
        }
        Console.WriteLine($"fuzz: {used} specials resolved, state checked after each; kinds {string.Join(" ", seenKinds.Select(k => k.Key + ":" + k.Value))}");
        if (seenKinds.Count < 10) throw new Exception("fuzz covered too few kinds");

        // 参考局面：施展者在平原，敌军在相邻、斜角、隔一格、同列隔一格（3500 兵、武 70、智 60，电脑阵型）
        var byKind = new Dictionary<string, List<KeyValuePair<string, double>>>();
        foreach (var name in ScenarioData.Generals.Select(l => l.Split('|')[0]))
        {
            var gen = g.generals.First(x => x.name == name);
            var sp = Specials.Of(gen);
            gen.troops = gen.MaxTroops; gen.training = 70;
            double r = RefRatio(g, fakeTarget, gen, sp, true);
            if (r > 0) Add(byKind, sp.kind, name, r);
        }
        var line = new List<string>(); KeyValuePair<string, double>? worst = null; string worstK = null;
        foreach (var k in byKind.Keys.OrderBy(k => k, StringComparer.Ordinal))
        {
            var rs = byKind[k].Select(o => o.Value).OrderBy(x => x).ToList();
            line.Add($"{k} {Sim.F(rs[0], 1)}-{Sim.F(rs[rs.Count - 1], 1)} (n{rs.Count})");
            if (DamageKinds.Contains(k)) foreach (var o in byKind[k]) if (worst == null || Math.Abs(Math.Log(o.Value / 2.1)) > Math.Abs(Math.Log(worst.Value.Value / 2.1))) { worst = o; worstK = k; }
        }
        Console.WriteLine("reference damage / normal action, by kind (damage kinds should sit near 1.8-2.5; roar/scheme/poison/assassinate are mostly control): " + string.Join("; ", line));
        var famous = new[] { "关羽", "吕布", "赵云", "黄忠", "孙策", "周瑜", "诸葛亮", "张飞" }.Select(nm =>
        {
            foreach (var k in byKind.Keys) { var o = byKind[k].FirstOrDefault(q => q.Key == nm); if (o.Key != null) return nm + " " + Sim.F(o.Value, 2); }
            return nm + " -";
        });
        Console.WriteLine("  hand-made: " + string.Join(", ", famous) + (worst != null ? $"; furthest from 2.1: {worst.Value.Key} ({worstK}) {Sim.F(worst.Value.Value, 2)}" : ""));
        foreach (var k in DamageKinds) if (byKind.ContainsKey(k)) foreach (var o in byKind[k]) if (!(o.Value > 1.2 && o.Value < 3.0)) throw new Exception("reference ratio out of range: " + o.Key + " " + k + " " + Sim.F(o.Value, 2));
    }
    static void Add(Dictionary<string, List<KeyValuePair<string, double>>> d, string k, string name, double v)
    {
        if (!d.ContainsKey(k)) d[k] = new List<KeyValuePair<string, double>>();
        d[k].Add(new KeyValuePair<string, double>(name, v));
    }
    // 参考局面的倍率 = 必杀技期望伤害（范围类最多计 2 支敌军；连斩计全部）÷ 普通一手
    static double RefRatio(GameState g, City target, General gen, Special sp, bool withKill)
    {
        var M = new BattleModel(Setup(g, target, new List<General> { gen }, new List<General> { Dummy(9001, "靶1", 70, 60), Dummy(9002, "靶2", 70, 60), Dummy(9003, "靶3", 70, 60), Dummy(9004, "靶4", 70, 60) }, 3000));
        for (int x = 1; x <= 7; x++) for (int y = 1; y <= 7; y++) M.map[x, y] = Terrain.Plain;
        var u = M.units[0]; var es = M.units.Skip(1).ToList();
        u.x = 4; u.y = 4; u.morale = 80;
        int[][] pos = { new[] { 5, 4 }, new[] { 5, 5 }, new[] { 4, 6 }, new[] { 4, 2 } };
        for (int k = 0; k < 4; k++) { es[k].x = pos[k][0]; es[k].y = pos[k][1]; es[k].morale = 70; }
        M.side = 0;
        double normal = Sim.RefAction(M, u, es[0], sp);
        double best = 0;
        foreach (var t in M.SpecialTargets(u))
        {
            var pl = M.SpecialPlan(u, t);
            var per = new Dictionary<BUnit, double>(); var order = new List<BUnit>();
            foreach (var h in pl.dmg)
            {
                if (!per.ContainsKey(h.unit)) { per[h.unit] = 0; order.Add(h.unit); }
                per[h.unit] = Math.Min(h.unit.Troops, per[h.unit] + h.amt * (h.onFail && pl.kill != null ? 1 - pl.kill.p : 1));
            }
            double dmg = order.Select(x => per[x]).OrderByDescending(x => x).Take(sp.kind == "rampage" ? 99 : 2).Sum();
            if (withKill && pl.kill != null) dmg += pl.kill.p * pl.kill.unit.Troops;
            best = Math.Max(best, dmg);
        }
        return best > 0 ? best / Math.Max(1, normal) : 0;
    }

    // --------------------------------------------------------------- (5b) 规则 --
    sealed class Field { public BattleModel M; public BUnit u; public List<BUnit> foes, friends; }
    static Field MakeField(GameState g, General casterGen, int casterSide, int nFoes, int nFriends = 0)
    {
        casterGen.troops = casterGen.MaxTroops; casterGen.training = 70;
        var mine = new List<General> { casterGen }; for (int i = 0; i < nFriends; i++) mine.Add(Dummy(9100 + 20 + i, "靶" + (20 + i), 70, 60));
        var theirs = new List<General>(); for (int i = 0; i < nFoes; i++) theirs.Add(Dummy(9100 + i, "靶" + i, 40, 30));
        var s = new BattleSetup { attacker = 0, defender = 1, src = g.cities[0], target = g.cities[11], atk = casterSide == 0 ? mine : theirs, def = casterSide == 0 ? theirs : mine, atkFood = 9000, atkGold = 0 };
        var M = new BattleModel(s);
        for (int x = 0; x < M.W; x++) for (int y = 0; y < M.H; y++) M.map[x, y] = Terrain.Plain;
        M.castle = new UnityEngine.Vector2Int(M.W - 1, M.H - 1);
        var u = M.units.First(x => x.gen == casterGen);
        var foes = M.units.Where(x => x.side != casterSide).ToList(); var friends = M.units.Where(x => x.side == casterSide && x != u).ToList();
        u.x = 5; u.y = 5;
        int[][] pos = { new[] { 6, 5 }, new[] { 5, 6 }, new[] { 4, 5 }, new[] { 5, 4 } };
        for (int k = 0; k < foes.Count && k < 4; k++) { foes[k].x = pos[k][0]; foes[k].y = pos[k][1]; }
        for (int k = 0; k < friends.Count; k++) { friends[k].x = 6 + k; friends[k].y = 4; }
        foreach (var x in M.units) { x.morale = 90; x.commander = false; }
        M.StartSide(casterSide);
        return new Field { M = M, u = u, foes = foes, friends = friends };
    }
    // 推进到下一次 side 一方行动开始（返回时 M.side == side）
    static void NextPhase(BattleModel M, int side) { do { M.EndSide(); } while (M.side != side && M.result == 0); }

    static void RulesCheck()
    {
        R.InitState(91);
        var g = GameState.Current = GameState.NewGame("cao");
        Func<string, General> byName = n => g.generals.FirstOrDefault(x => x.name == n);
        var lines = new List<string>();
        // (a) 混乱：无论攻方或守方施展，「混乱 N 日」都让目标恰好失去 N 次本方行动
        var allSp = Specials.All();
        var confusers = new[] { allSp.First(sp => sp.kind == "roar" && sp.turns == 1 && sp.confuse > 0), allSp.First(sp => sp.kind == "scheme" && sp.turns == 2) };
        foreach (var sp in confusers)
            for (int side = 0; side <= 1; side++)
            {
                var f = MakeField(g, byName(sp.gen), side, 2);
                var t = Specials.NeedsTarget(sp) ? f.foes[0] : f.u;
                SpecialResult res;
                R.ValueOverride = () => 0;            // 必定成功
                try { res = f.M.UseSpecial(f.u, t); } finally { R.ValueOverride = null; }
                if (res.confused.Count == 0) throw new Exception(sp.name + " confused nobody");
                var e = res.confused[0];
                int lost = 0;
                for (int k = 0; k < 4; k++) { NextPhase(f.M, e.side); if (!f.M.CanAct(e)) lost++; }
                lines.Add($"{sp.gen}「{sp.name}」混乱 {sp.Turns} 日 by side {side}: lost {lost}");
                if (lost != sp.Turns) throw new Exception($"{sp.name} (turns {sp.Turns}) cast by side {side}: target lost {lost} phases");
            }
        // (b) 加成：持续 N 日 = 覆盖敌方 N 次行动（以及本方之后 N−1 次行动），攻守相同
        foreach (var name in new[] { "法正", "曹洪", "典韦", "曹操" })
        {
            var sp = Specials.Of(byName(name));
            for (int side = 0; side <= 1; side++)
            {
                var f = MakeField(g, byName(name), side, 1, 1);
                var res = f.M.UseSpecial(f.u, f.u);
                if (res.buffed.Count == 0) throw new Exception(name + " buffed nobody");
                var a = res.buffed[0];
                string key = sp.def > 1 ? "def" : "atk";
                int enemy = 0, own = 0;
                for (int k = 0; k < 4; k++)
                {
                    NextPhase(f.M, 1 - side); if (f.M.ModK(a, key) > 1) enemy++;
                    NextPhase(f.M, side); if (f.M.ModK(a, key) > 1) own++;
                }
                lines.Add($"{name}「{sp.name}」{key} {sp.Turns} 日 by side {side}: enemy phases {enemy}, later own phases {own}");
                if (enemy != sp.Turns || own != sp.Turns - 1) throw new Exception($"{name} ({key}, turns {sp.Turns}) by side {side}: covers {enemy} enemy / {own} own phases");
            }
        }
        // (c) 中毒：发作次数 = 持续日数，攻守相同
        {
            var sp = Specials.Of(byName("李儒"));
            for (int side = 0; side <= 1; side++)
            {
                var f = MakeField(g, byName("李儒"), side, 1);
                f.foes[0].x = 7; f.foes[0].y = 5;
                f.M.UseSpecial(f.u, f.foes[0]);
                var e = f.foes[0];
                int ticks = 0;
                for (int k = 0; k < 6 && e.alive; k++) { int before = e.Troops; NextPhase(f.M, side); if (e.Troops < before) ticks++; }
                lines.Add($"李儒「{sp.name}」中毒 {sp.Turns} 日 by side {side}: ticks {ticks}");
                if (ticks != sp.Turns) throw new Exception($"poison by side {side} ticked {ticks} times (turns {sp.Turns})");
            }
        }
        Console.WriteLine("  " + string.Join("\n  ", lines));
        // (d) 突击不能把本城 / 城门上的部队撞走
        {
            int n = 0;
            foreach (var sp in Specials.All().Where(q => q.kind == "charge" && q.push != 0 && byName(q.gen) != null).ToList())
                foreach (var tile in new[] { Terrain.Castle, Terrain.Gate })
                {
                    var f = MakeField(g, byName(sp.gen), 0, 1);
                    var t = f.foes[0];
                    t.x = 9; t.y = 5; f.u.x = 9 - sp.Range; f.u.y = 5;
                    f.M.map[t.x, t.y] = tile; if (tile == Terrain.Castle) f.M.castle = new UnityEngine.Vector2Int(t.x, t.y);
                    t.commander = tile == Terrain.Castle;
                    var pl = f.M.SpecialPlan(f.u, t);
                    if (pl.push != null || pl.blocked != t) throw new Exception(sp.gen + " charge would push a unit off " + (tile == Terrain.Castle ? "本城" : "城门"));
                    f.M.UseSpecial(f.u, t);
                    if (t.alive && (t.x != 9 || t.y != 5)) throw new Exception(sp.gen + " charge moved the defender off its tile");
                    n++;
                }
            Console.WriteLine($"  charge vs 本城 / 城门: {n} cases, defender never pushed off");
        }
        // (e) 每位手写武将的伤害倍率：单体与密集（主目标周围再有 3 支敌军）
        var single = new Dictionary<string, List<KeyValuePair<string, double>>>(); var cluster = new Dictionary<string, List<KeyValuePair<string, double>>>();
        string worstName = null, worstKind = null; double worstX = -1;
        foreach (var name in ScenarioData.Generals.Select(l => l.Split('|')[0]))
        {
            var gen = byName(name);
            var sp = Specials.Of(gen);
            if (!DamageKinds.Contains(sp.kind)) continue;
            foreach (var mode in new[] { "single", "cluster" })
            {
                var f = MakeField(g, gen, 0, mode == "single" ? 1 : 4);
                var t = f.foes[0];
                int r = sp.kind == "cleave" || sp.kind == "rampage" || sp.kind == "drain" || sp.kind == "smite" ? 1 : Math.Max(1, Math.Min(sp.Range, 3));
                t.x = 5 + r; t.y = 5;
                if (mode == "cluster")
                {
                    int[][] spots = sp.kind == "cleave" || sp.kind == "rampage" ? new[] { new[] { 5, 6 }, new[] { 4, 5 }, new[] { 5, 4 } } : new[] { new[] { t.x, 6 }, new[] { t.x, 4 }, new[] { t.x + 1, 5 } };
                    for (int k = 1; k < f.foes.Count; k++) { f.foes[k].x = spots[k - 1][0]; f.foes[k].y = spots[k - 1][1]; }
                }
                if (f.M.SpecialTargets(f.u).IndexOf(t) < 0) continue;
                var pl = f.M.SpecialPlan(f.u, t);
                var per = new Dictionary<BUnit, double>();
                foreach (var h in pl.dmg) per[h.unit] = Math.Min(h.unit.Troops, (per.ContainsKey(h.unit) ? per[h.unit] : 0) + h.amt);
                double tot = per.Values.Sum();
                if (pl.drain > 0) foreach (var h in pl.dmg) if (h.primary) tot += Math.Min(h.unit.Troops, h.amt) * pl.drain;   // 收编：伤敌 + 己方增兵
                double x = tot / Math.Max(1, Sim.RefAction(f.M, f.u, t, sp));
                Add(mode == "single" ? single : cluster, sp.kind, name, x);
                if (mode == "cluster" && x > worstX) { worstX = x; worstName = name; worstKind = sp.kind; }
            }
        }
        Func<Dictionary<string, List<KeyValuePair<string, double>>>, string> fmtK = o => string.Join(", ", o.Keys.OrderBy(k => k, StringComparer.Ordinal).Select(k =>
        {
            var xs = o[k].Select(q => q.Value).ToList();
            return $"{k} {Sim.F(Sim.Median(xs), 2)} [{Sim.F(xs.Min(), 2)}-{Sim.F(xs.Max(), 2)}]";
        }));
        Console.WriteLine("  single target, median [min-max] of special / normal action (drain counts troops gained): " + fmtK(single));
        Console.WriteLine("  4 clustered foes, total: " + fmtK(cluster) + $"; highest {worstName} ({worstKind}) {Sim.F(worstX, 2)}");
        foreach (var k in single.Keys)
        {
            double m = Sim.Median(single[k].Select(q => q.Value).ToList());
            double lo = new[] { "smite", "charge", "rampage", "drain" }.Contains(k) ? 1.6 : k == "storm" || k == "flood" ? 0.5 : 0.9;
            if (!(m >= lo && m <= 2.6)) throw new Exception($"single-target median for {k} = {Sim.F(m, 2)} (want {lo}-2.6)");
            foreach (var o in single[k]) if (!(o.Value <= 3.0)) throw new Exception($"single-target {o.Key} ({k}) = {Sim.F(o.Value, 2)} > 3.0");
        }
        foreach (var k in cluster.Keys) foreach (var o in cluster[k]) if (!(o.Value <= 3.2)) throw new Exception($"clustered {o.Key} ({k}) = {Sim.F(o.Value, 2)} > 3.2");
        Console.WriteLine("specials rules OK");
    }

    // ---------------------------------------------------------- (5c) 世界武将 --
    static void World()
    {
        var classicNames = new HashSet<string>(ScenarioData.Generals.Select(l => l.Split('|')[0]));
        var wroster = WorldScenarioData.Generals.Select(l => { var p = l.Split('|'); return new General { name = p[0], war = int.Parse(p[1]), intel = int.Parse(p[2]), pol = int.Parse(p[3]), culture = p.Length > 9 && p[9].Length > 0 ? p[9] : "han" }; }).ToList();
        GameState.Current = null;
        var rep = Specials.Check(wroster);
        Console.WriteLine($"world roster {wroster.Count}: specials {rep.total}, hand-made {rep.hand}, generated {rep.auto}; duplicate names {rep.dupNames.Count}, duplicate (kind, params) {rep.dupSigs.Count}, data problems {rep.problems.Count}");
        foreach (var p in rep.problems) Console.WriteLine("  problem: " + p);
        if (!rep.ok) throw new Exception("world specials self-check failed");
        var fresh = wroster.Where(x => !classicNames.Contains(x.name)).ToList();
        var autoW = fresh.Where(x => Specials.Of(x).auto).Select(x => x.name).ToList();
        if (autoW.Count > 0) throw new Exception("world generals without a hand-made special: " + string.Join(" ", autoW));
        foreach (var x in fresh) { var nm = Specials.Of(x).name; if (nm.Length < 2 || nm.Length > 5) throw new Exception("special name should be 2-5 chars: " + x.name + " " + nm); }
        var kinds = new SortedDictionary<string, int>(StringComparer.Ordinal);
        foreach (var x in fresh) { var k = Specials.Of(x).kind; kinds[k] = (kinds.ContainsKey(k) ? kinds[k] : 0) + 1; }
        Console.WriteLine($"{fresh.Count} new world generals, all hand-made; kinds {string.Join(" ", kinds.Select(k => k.Key + ":" + k.Value))}");
        R.InitState(778);
        var g = GameState.Current = GameState.NewGame("cao");
        var byKind = new Dictionary<string, List<KeyValuePair<string, double>>>();
        for (int i = 0; i < fresh.Count; i++)
        {
            var w = fresh[i];
            var gen = new General { id = 9600 + i, name = w.name, war = w.war, intel = w.intel, pol = w.pol, faction = -1, troops = 0, training = 70, loyalty = 90, culture = w.culture };
            gen.troops = gen.MaxTroops;
            var sp = Specials.Of(gen);
            if (!DamageKinds.Contains(sp.kind)) continue;
            Add(byKind, sp.kind, w.name, RefRatio(g, g.cities[11], gen, sp, false));
        }
        Console.WriteLine("world reference damage / normal action: " + string.Join("; ", byKind.Keys.OrderBy(k => k, StringComparer.Ordinal).Select(k =>
        {
            var rs = byKind[k].Select(o => o.Value).OrderBy(x => x).ToList();
            return $"{k} {Sim.F(rs[0], 1)}-{Sim.F(rs[rs.Count - 1], 1)} (n{rs.Count})";
        })));
        foreach (var k in byKind.Keys) foreach (var o in byKind[k]) if (!(o.Value > 1.2 && o.Value < 3.0)) throw new Exception("world reference ratio out of range: " + o.Key + " " + k + " " + Sim.F(o.Value, 2));
        Console.WriteLine("world specials OK");
    }

    // --------------------------------------------------------------- (6) 单挑 --
    // 未拆分的单挑（第一版的写法，数值与 JS 相同）：与拆分后的 Duel() 在相同随机数下结果必须完全一致
    static DuelResult DuelV1(BattleModel M, BUnit a, BUnit b)
    {
        var r = new DuelResult();
        r.accepted = b.gen.war >= a.gen.war - 8 || R.value < 0.25f || (b.commander && R.value < 0.4f);
        if (!r.accepted) { b.morale = Math.Max(0, b.morale - 12); a.morale = Math.Min(100, a.morale + 8); return r; }
        int hpA = 100, hpB = 100;
        for (int i = 0; i < 30 && hpA > 0 && hpB > 0; i++)
        {
            int who = R.value < (double)a.gen.war / (a.gen.war + b.gen.war) ? 0 : 1;
            var striker = who == 0 ? a : b;
            int dmg = (int)Math.Round(R.Range(6, 16) * (0.6 + striker.gen.war / 120.0));
            if (who == 0) hpB = Math.Max(0, hpB - dmg); else hpA = Math.Max(0, hpA - dmg);
            r.rounds.Add(new DuelRound { who = who, dmg = dmg, hpA = hpA, hpB = hpB });
        }
        r.winner = hpA >= hpB ? 0 : 1;
        var loser = r.winner == 0 ? b : a; var winner = r.winner == 0 ? a : b;
        loser.Troops = 0; loser.alive = false; M.setup.routed.Add(loser.gen.id);
        foreach (var o in M.Alive(loser.side)) o.morale = Math.Max(0, o.morale - 8);
        winner.morale = Math.Min(100, winner.morale + 15);
        M.CheckEnd();
        return r;
    }
    static void DuelSplit()
    {
        int n = 0;
        for (int seed = 1; seed <= 60; seed++)
        {
            var pr = Sim.Pairs[seed % Sim.Pairs.Length];
            var snap = new List<string>();
            for (int v = 0; v <= 1; v++)
            {
                R.InitState(seed * 31);
                var g = GameState.Current = GameState.NewGame("cao");
                var src = g.CityByKey(pr[0]); var tgt = g.CityByKey(pr[1]);
                var s = Conquest.Prepare(src.owner, src, tgt, g.OfficersIn(src).Where(x => x.troops > 0).Take(5).ToList(), 3000, 0);
                var M = new BattleModel(s);
                var a = M.units[seed % M.Alive(0).Count()]; var b = M.Alive(1).ToList()[seed % M.Alive(1).Count()];
                var r = v == 0 ? DuelV1(M, a, b) : M.Duel(a, b);
                snap.Add($"{r.accepted}|{r.winner}|{string.Join(";", r.rounds.Select(q => q.who + "," + q.dmg + "," + q.hpA + "," + q.hpB))}|next {R.NextDouble():R}|{string.Join(";", M.units.Select(u => u.Troops + "," + u.morale + "," + u.alive))}|{M.result}|{string.Join(",", s.routed)}");
            }
            if (snap[0] != snap[1]) throw new Exception("duel differs at seed " + seed + "\n" + snap[0] + "\n" + snap[1]);
            n++;
        }
        // DuelAccepts + DuelFinish 组合与 Duel() 的后果一致
        R.InitState(5);
        var g2 = GameState.Current = GameState.NewGame("cao");
        var src2 = g2.CityByKey("chenliu"); var tgt2 = g2.CityByKey("luoyang");
        var s2 = Conquest.Prepare(src2.owner, src2, tgt2, g2.OfficersIn(src2).Where(x => x.troops > 0).Take(5).ToList(), 3000, 0);
        var M2 = new BattleModel(s2);
        var a2 = M2.Alive(0).ToList()[1]; var b2 = M2.Alive(1).ToList()[1];
        if (M2.DuelAccepts(a2, b2) != true && b2.gen.war >= a2.gen.war - 8) throw new Exception("DuelAccepts should accept equal opponents");
        var fin = M2.DuelFinish(a2, b2, true, new List<DuelRound> { new DuelRound { who = 0, dmg = 100, hpA = 100, hpB = 0 } });
        if (b2.alive || !a2.alive || fin.winner != 0 || !s2.routed.Contains(b2.gen.id)) throw new Exception("DuelFinish did not resolve the duel");
        Console.WriteLine($"duel split OK ({n} seeds identical to v1)");
    }
}
