from common import *

def stance_aura(id_, name, icon, desc, mods):
    return aura(id_, name, icon, desc, kind="Buff", duration=0, exclusiveGroup="warrior_stance", tags=["Stance"],
                persistThroughDeath=True, mods=mods)

def debuff(id_, name, icon, desc, duration, **kw):
    return aura(id_, name, icon, desc, kind="Debuff", duration=duration, **kw)

def buff(id_, name, icon, desc, duration, **kw):
    return aura(id_, name, icon, desc, kind="Buff", duration=duration, **kw)

AURAS = [
    stance_aura("warrior_battle_stance_aura", "Battle Stance", "stance_battle", "Generates 20% less threat.",
                [mod("ThreatGenerated", -20, pct=True)]),
    stance_aura("warrior_defensive_stance_aura", "Defensive Stance", "stance_defensive",
                "Damage taken and damage caused reduced by 10%. Threat generated increased by 30%.",
                [mod("DamageTaken", -10, pct=True), mod("DamageDone", -10, pct=True), mod("ThreatGenerated", 30, pct=True)]),
    stance_aura("warrior_berserker_stance_aura", "Berserker Stance", "stance_berserker",
                "Critical hit chance increased by 3%. Damage taken increased by 10%. Generates 20% less threat.",
                [mod("MeleeCrit", 3), mod("DamageTaken", 10, pct=True), mod("ThreatGenerated", -20, pct=True)]),

    debuff("warrior_charge_stun", "Charge Stun", "charge", "Stunned.", 1, states=["Stun"], tags=["Stun"]),
    debuff("warrior_rend", "Rend", "blood", "Bleeding for Physical damage every 3 sec.", 21, tags=["Bleed"],
           tickInterval=3, tickEffects=[E("Damage", min=2.14, perLevel=0.3375)]),
    debuff("warrior_thunder_clap", "Thunder Clap", "lightning", "Attack speed reduced by 10%.", 10,
           special="RankDurations", tags=["Durations:10/14/18/22/26/30"],
           mods=[mod("MeleeHaste", -10, pct=True), mod("RangedHaste", -10, pct=True)]),
    debuff("warrior_hamstring", "Hamstring", "boot", "Movement speed reduced by 50%.", 15, tags=["Snare"],
           mods=[mod("MoveSpeed", -50, pct=True)]),
    debuff("warrior_improved_hamstring", "Improved Hamstring", "boot", "Immobilized.", 5, tags=["Root"], states=["Root"]),
    buff("warrior_bloodrage", "Bloodrage", "rage", "Generating 1 rage per second.", 10,
         tickInterval=1, tickEffects=[E("GainResource", resource="Rage", amount=1)]),
    buff("warrior_battle_shout", "Battle Shout", "shout", "Melee attack power increased.", 120, tags=["Shout"],
         mods=[vmod("AttackPower", [20, 40, 57, 93, 138, 193])]),
    debuff("warrior_demoralizing_shout", "Demoralizing Shout", "shout", "Melee attack power reduced.", 30,
           tags=["Shout"], mods=[vmod("AttackPower", [-35, -55, -73, -103, -140])]),
    debuff("warrior_sunder_armor", "Sunder Armor", "armor", "Armor reduced per application (up to 5).", 30,
           maxStacks=5, mods=[vmod("Armor", [-90, -180, -270, -360, -450])]),
    buff("warrior_shield_block", "Shield Block", "shield", "Block chance increased by 75%. Blocks 1 attack.", 5,
         charges=1, mods=[mod("Block", 75)], procs=[proc("OnBlock", [], consumeCharge=True)]),
    debuff("warrior_disarm", "Disarm", "hand", "Disarmed: weapon damage greatly reduced.", 10, states=["Disarm"]),
    buff("warrior_retaliation", "Retaliation", "swords",
         "Counterattacking any enemy that strikes you in melee (not from behind). Up to 30 counterattacks.", 15,
         charges=30, procs=[proc("OnStruck", [E("WeaponDamage", target="Attacker", weaponPct=100)], consumeCharge=True)]),
    debuff("warrior_intimidating_shout_cower", "Intimidating Shout", "fear", "Cowering in fear, unable to move or act.",
           8, states=["Fear", "Root"], breakOnDamage=True, tags=["Fear"]),
    debuff("warrior_intimidating_shout_fear", "Intimidating Shout", "fear", "Fleeing in fear.", 8, states=["Fear"],
           breakOnDamage=True, tags=["Fear"]),
    buff("warrior_shield_wall", "Shield Wall", "shield", "All damage taken reduced by 75%.", 10,
         mods=[mod("DamageTaken", -75, pct=True)]),
    debuff("warrior_intercept_stun", "Intercept Stun", "charge", "Stunned.", 3, states=["Stun"], tags=["Stun"]),
    buff("warrior_berserker_rage", "Berserker Rage", "rage",
         "Immune to Fear, Sap and Incapacitate effects. Generating extra rage when taking damage.", 10,
         tags=["ImmuneFear", "ImmuneIncapacitate"], special="WarriorBerserkerRage"),
    buff("warrior_recklessness", "Recklessness", "rage",
         "Critical hits with most attacks. Immune to Fear. Damage taken increased by 20%.", 15,
         tags=["ImmuneFear"], special="ImmunityFromTags",
         mods=[mod("MeleeCrit", 100), mod("DamageTaken", 20, pct=True)]),

    # talent auras
    buff("warrior_sweeping_strikes", "Sweeping Strikes", "whirlwind",
         "Your next 5 melee weapon swings strike an additional nearby opponent.", 10, charges=5, special="SweepingHits"),
    debuff("warrior_mortal_strike", "Mortal Strike", "sword", "Healing effects reduced by 50%.", 10,
           mods=[mod("HealingTaken", -50, pct=True)]),
    debuff("warrior_piercing_howl", "Piercing Howl", "shout", "Dazed: movement speed reduced by 50%.", 6,
           tags=["Snare"], states=["Daze"]),
    buff("warrior_death_wish", "Death Wish", "skull",
         "Physical damage increased by 20%. Immune to Fear. Armor and resistances reduced by 20%.", 30,
         tags=["ImmuneFear"], special="ImmunityFromTags",
         mods=[mod("DamageDone", 20, pct=True, school="Physical"), mod("Armor", -20, pct=True),
               mod("Resistance", -20, pct=True)]),
    buff("warrior_bloodthirst", "Bloodthirst", "blood", "Your next 5 successful melee attacks restore health.", 8,
         charges=5, procs=[proc("OnMeleeHit", [E("Heal", target="Self", min=10, perLevel=0.5)], consumeCharge=True)]),
    buff("warrior_last_stand", "Last Stand", "heart", "Maximum health increased by 30%.", 20,
         mods=[mod("Health", 30, pct=True)], onApply=[E("Heal", pctOfMax=23.1)]),
    debuff("warrior_concussion_blow", "Concussion Blow", "hammer", "Stunned.", 5, states=["Stun"], tags=["Stun"]),
    debuff("warrior_deep_wounds", "Deep Wounds", "blood", "Bleeding for a portion of the warrior's weapon damage.", 12,
           tags=["Bleed"], tickInterval=3, tickEffects=[E("WeaponDamage", weaponPct=15, cannotMiss=True, cannotCrit=True)]),
    buff("warrior_enrage", "Enrage", "rage", "Melee damage increased for up to 12 swings.", 12, charges=12,
         mods=[vmod("DamageDone", [5, 10, 15, 20, 25], pct=True, school="Physical")], procs=[proc("OnMeleeHit", [], consumeCharge=True)]),
    buff("warrior_flurry", "Flurry", "whirlwind", "Attack speed increased for the next 3 swings.", 15, charges=3,
         mods=[vmod("MeleeHaste", [10, 15, 20, 25, 30], pct=True)], procs=[proc("OnAutoAttackHit", [], consumeCharge=True)]),
    buff("warrior_blood_craze", "Blood Craze", "blood", "Regenerating 3% of total health over 6 sec.", 6,
         tickInterval=3, tickEffects=[E("Heal", pctOfMax=1.5)]),
    debuff("warrior_revenge_stun", "Revenge Stun", "shield", "Stunned.", 3, states=["Stun"], tags=["Stun"]),
    debuff("warrior_mace_stun", "Mace Stun Effect", "mace", "Stunned.", 3, states=["Stun"], tags=["Stun"]),
    debuff("warrior_shield_bash_silence", "Shield Bash - Silenced", "shield_bash", "Silenced.", 3, states=["Silence"]),
]
