from common import *

A = "warrior_arms_"
F = "warrior_fury_"
P = "warrior_protection_"

def used(ability, effects, chance=None):
    p = proc("OnAbilityUsed", effects, abilities=[ability])
    if chance is not None:
        p["chance"] = chance
    return p

def rage_self(amount, per_rank=0):
    e = E("GainResource", target="Self", resource="Rage", amount=amount)
    if per_rank:
        e["perLevel"] = per_rank
    return e

def two_step(ability, first, second):
    """Rank 1 grants `first` rage, rank 2 grants first+second (two procs; values = chance per rank)."""
    return [P_proc(used(ability, [rage_self(first)]), values=[100, 100]),
            P_proc(used(ability, [rage_self(second)]), values=[0, 100])]

def wtt(desc_tags, **kw):
    return P_special("WeaponTypeTalent", tags=desc_tags, **kw)

IMPALE_ABILITIES = ["warrior_heroic_strike", "warrior_cleave", "warrior_overpower", "warrior_thunder_clap",
                    "warrior_hamstring", "warrior_revenge", "warrior_mocking_blow", "warrior_execute", "warrior_slam",
                    "warrior_whirlwind", "warrior_intercept", "warrior_pummel", "warrior_shield_bash",
                    "warrior_mortal_strike", "warrior_bloodthirst", "warrior_shield_slam"]

ARMS = {
    "id": "tree_warrior_arms", "classId": "Warrior", "name": "Arms", "icon": "swords",
    "description": "A battle-hardened master of weapons, using mobility and overpowering attacks to strike opponents down.",
    "talents": [
        T(A + "improved_heroic_strike", "Improved Heroic Strike", "sword", 1, 0, 3,
          "Reduces the cost of your Heroic Strike ability by {1/2/3} rage points.",
          [P_mod("CostFlat", -1, abilities=["warrior_heroic_strike"])]),
        T(A + "deflection", "Deflection", "shield", 1, 1, 5, "Increases your Parry chance by {1/2/3/4/5}%.",
          [P_stat("Parry", 1)]),
        T(A + "improved_rend", "Improved Rend", "blood", 1, 2, 3,
          "Increases the bleed damage done by your Rend ability by {15/25/35}%.",
          [P_mod("Effect", values=[15, 25, 35], abilities=["warrior_rend"])]),
        T(A + "improved_charge", "Improved Charge", "charge", 2, 0, 2,
          "Increases the amount of rage generated by your Charge ability by {3/6}.",
          two_step("warrior_charge", 3, 3)),
        T(A + "tactical_mastery", "Tactical Mastery", "stance_battle", 2, 1, 5,
          "You retain up to {5/10/15/20/25} of your rage points when you change stances.",
          [P_special("WarriorStanceSwap", value=5)]),
        T(A + "improved_thunder_clap", "Improved Thunder Clap", "lightning", 2, 3, 3,
          "Reduces the cost of your Thunder Clap ability by {1/2/4} rage points.",
          [P_mod("CostFlat", values=[-1, -2, -4], abilities=["warrior_thunder_clap"])]),
        T(A + "improved_overpower", "Improved Overpower", "swords", 3, 0, 2,
          "Increases the critical strike chance of your Overpower ability by {25/50}%.",
          [P_mod("CritChance", 25, abilities=["warrior_overpower"])]),
        T(A + "anger_management", "Anger Management", "rage", 3, 1, 1,
          "Generates 1 rage point every 3 sec (2 rage at the start of each of your turns in combat).",
          [P_proc(proc("OnTurnStart", [rage_self(2)]))], requires=A + "tactical_mastery"),
        T(A + "deep_wounds", "Deep Wounds", "blood", 3, 2, 3,
          "Your critical strikes cause the opponent to bleed, dealing {20/40/60}% of your melee weapon's average damage "
          "over 12 sec.",
          [P_proc(proc("OnMeleeCrit", [E("ApplyAura", aura="warrior_deep_wounds")]), values=[33.3, 66.7, 100])],
          requires=A + "improved_rend"),
        T(A + "two_handed_weapon_specialization", "Two-Handed Weapon Specialization", "sword", 4, 1, 5,
          "Increases the damage you deal with two-handed melee weapons by {1/2/3/4/5}%.",
          [wtt(["TwoHanded"], stat="DamageDone", value=1, pct=True)]),
        T(A + "impale", "Impale", "spear", 4, 2, 2,
          "Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by "
          "{10/20}%.",
          [P_mod("CritBonus", 10, abilities=IMPALE_ABILITIES)], requires=A + "deep_wounds"),
        T(A + "axe_specialization", "Axe Specialization", "axe", 5, 0, 5,
          "Increases your chance to get a critical strike with Axes by {1/2/3/4/5}%.",
          [wtt(["OneHandAxe", "TwoHandAxe"], stat="MeleeCrit", value=1)]),
        T(A + "sweeping_strikes", "Sweeping Strikes", "whirlwind", 5, 1, 1, "Grants the Sweeping Strikes ability.",
          [P_grant("warrior_sweeping_strikes")]),
        T(A + "mace_specialization", "Mace Specialization", "mace", 5, 2, 5,
          "Gives you a {1/2/3/4/5}% chance to stun your target for 3 sec with a Mace.",
          [wtt(["OneHandMace", "TwoHandMace"], values=[1, 2, 3, 4, 5],
               proc=proc("OnMeleeHit", [E("ApplyAura", aura="warrior_mace_stun")]))]),
        T(A + "sword_specialization", "Sword Specialization", "sword", 5, 3, 5,
          "Gives you a {1/2/3/4/5}% chance to get an extra attack on the same target after dealing damage with your "
          "Sword.",
          [wtt(["OneHandSword", "TwoHandSword"], values=[1, 2, 3, 4, 5],
               proc=proc("OnMeleeHit", [E("WeaponDamage", weaponPct=100)]))]),
        T(A + "polearm_specialization", "Polearm Specialization", "spear", 6, 0, 5,
          "Increases your chance to get a critical strike with Polearms by {1/2/3/4/5}%.",
          [wtt(["Polearm"], stat="MeleeCrit", value=1)]),
        T(A + "improved_hamstring", "Improved Hamstring", "boot", 6, 2, 3,
          "Gives your Hamstring ability a {5/10/15}% chance to immobilize the target for 5 sec.",
          [P_proc(used("warrior_hamstring", [E("ApplyAura", aura="warrior_improved_hamstring")]), values=[5, 10, 15])]),
        T(A + "mortal_strike", "Mortal Strike", "sword", 7, 1, 1, "Grants the Mortal Strike ability.",
          [P_grant("warrior_mortal_strike")], requires=A + "sweeping_strikes"),
    ],
}

FURY = {
    "id": "tree_warrior_fury", "classId": "Warrior", "name": "Fury", "icon": "rage",
    "description": "A furious berserker wielding a weapon in each hand, unleashing a flurry of attacks.",
    "talents": [
        T(F + "booming_voice", "Booming Voice", "shout", 1, 1, 5,
          "Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by "
          "{10/20/30/40/50}%.",
          [P_mod("DurationPct", 10, abilities=["warrior_battle_shout", "warrior_demoralizing_shout"]),
           P_mod("Radius", 10, abilities=["warrior_battle_shout", "warrior_demoralizing_shout"])]),
        T(F + "cruelty", "Cruelty", "sword", 1, 2, 5,
          "Increases your chance to get a critical strike with melee weapons by {1/2/3/4/5}%.",
          [P_stat("MeleeCrit", 1)]),
        T(F + "improved_demoralizing_shout", "Improved Demoralizing Shout", "shout", 2, 1, 5,
          "Increases the melee attack power reduction of your Demoralizing Shout by {8/16/24/32/40}%.",
          [P_mod("Effect", 8, abilities=["warrior_demoralizing_shout"])]),
        T(F + "unbridled_wrath", "Unbridled Wrath", "rage", 2, 2, 5,
          "Gives you a {8/16/24/32/40}% chance to generate an additional rage point when you deal melee damage with "
          "a weapon.",
          [P_proc(proc("OnMeleeHit", [rage_self(1)]), values=[8, 16, 24, 32, 40])]),
        T(F + "improved_cleave", "Improved Cleave", "axe", 3, 0, 3,
          "Increases the bonus damage done by your Cleave ability by {40/80/120}%.",
          [P_special("WarriorImprovedCleave", value=40)]),
        T(F + "piercing_howl", "Piercing Howl", "shout", 3, 1, 1, "Grants the Piercing Howl ability.",
          [P_grant("warrior_piercing_howl")]),
        T(F + "blood_craze", "Blood Craze", "blood", 3, 2, 3,
          "Regenerates {1/2/3}% of your total Health over 6 sec after being the victim of a critical strike.",
          [P_proc(proc("OnCritTaken", [E("ApplyAura", target="Self", aura="warrior_blood_craze")]),
                  values=[3.3, 6.7, 10])]),
        T(F + "improved_battle_shout", "Improved Battle Shout", "shout", 3, 3, 5,
          "Increases the melee attack power bonus of your Battle Shout by {5/10/15/20/25}%.",
          [P_mod("Effect", 5, abilities=["warrior_battle_shout"])]),
        T(F + "dual_wield_specialization", "Dual Wield Specialization", "swords", 4, 0, 5,
          "Increases the damage done by your offhand weapon by {5/10/15/20/25}%.",
          [P_special("OffHandDamage", value=5)]),
        T(F + "improved_execute", "Improved Execute", "skull", 4, 1, 2,
          "Reduces the rage cost of your Execute ability by {2/5}.",
          [P_mod("CostFlat", values=[-2, -5], abilities=["warrior_execute"])]),
        T(F + "enrage", "Enrage", "rage", 4, 2, 5,
          "Gives you a {5/10/15/20/25}% melee damage bonus for 12 sec up to a maximum of 12 swings after being the "
          "victim of a critical strike.",
          [P_proc(proc("OnCritTaken", [E("ApplyAura", target="Self", aura="warrior_enrage")]))]),
        T(F + "improved_slam", "Improved Slam", "hammer", 5, 0, 5,
          "Decreases the casting time of your Slam ability by {0.1/0.2/0.3/0.4/0.5} sec.",
          [P_mod("CastTime", -0.1, abilities=["warrior_slam"])]),
        T(F + "death_wish", "Death Wish", "skull", 5, 1, 1, "Grants the Death Wish ability.",
          [P_grant("warrior_death_wish")]),
        T(F + "improved_intercept", "Improved Intercept", "charge", 5, 3, 2,
          "Reduces the cooldown of your Intercept ability by {5/10} sec.",
          [P_mod("Cooldown", -5, abilities=["warrior_intercept"])]),
        T(F + "improved_berserker_rage", "Improved Berserker Rage", "rage", 6, 0, 2,
          "The Berserker Rage ability will generate {5/10} rage when used.",
          two_step("warrior_berserker_rage", 5, 5)),
        T(F + "flurry", "Flurry", "whirlwind", 6, 2, 5,
          "Increases your attack speed by {10/15/20/25/30}% for your next 3 swings after dealing a melee critical "
          "strike.",
          [P_proc(proc("OnMeleeCrit", [E("ApplyAura", target="Self", aura="warrior_flurry")]))], requires=F + "enrage"),
        T(F + "bloodthirst", "Bloodthirst", "blood", 7, 1, 1, "Grants the Bloodthirst ability.",
          [P_grant("warrior_bloodthirst")]),
    ],
}

PROT = {
    "id": "tree_warrior_protection", "classId": "Warrior", "name": "Protection", "icon": "shield",
    "description": "A stalwart protector who uses a shield to safeguard themselves and their allies.",
    "talents": [
        T(P + "shield_specialization", "Shield Specialization", "shield", 1, 1, 5,
          "Increases your chance to block attacks with a shield by {1/2/3/4/5}% and has a {20/40/60/80/100}% chance "
          "to generate 1 rage when a block occurs.",
          [P_stat("Block", 1), P_proc(proc("OnBlock", [rage_self(1)]), values=[20, 40, 60, 80, 100])]),
        T(P + "anticipation", "Anticipation", "eye", 1, 2, 5, "Increases your Defense skill by {2/4/6/8/10}.",
          [P_stat("Defense", 2)]),
        T(P + "improved_bloodrage", "Improved Bloodrage", "rage", 2, 0, 2,
          "Increases the instant rage generated by your Bloodrage ability by {2/5}.",
          two_step("warrior_bloodrage", 2, 3)),
        T(P + "toughness", "Toughness", "armor", 2, 2, 5, "Increases your armor value from items by {2/4/6/8/10}%.",
          [P_stat("Armor", 2, pct=True)]),
        T(P + "iron_will", "Iron Will", "shield", 2, 3, 5,
          "Increases your chance to resist Stun and Charm effects by an additional {3/6/9/12/15}%.",
          [P_special("WarriorIronWill", value=3)]),
        T(P + "last_stand", "Last Stand", "heart", 3, 0, 1, "Grants the Last Stand ability.",
          [P_grant("warrior_last_stand")], requires=P + "improved_bloodrage"),
        T(P + "improved_shield_block", "Improved Shield Block", "shield", 3, 1, 3,
          "Allows your Shield Block ability to block an additional attack and increases the duration by {0.5/1/2} sec.",
          [P_mod("Duration", values=[0.5, 1, 2], abilities=["warrior_shield_block"]),
           P_mod("Charges", values=[1, 1, 1], abilities=["warrior_shield_block"])],
          requires=P + "shield_specialization"),
        T(P + "improved_revenge", "Improved Revenge", "shield", 3, 2, 3,
          "Gives your Revenge ability a {15/30/45}% chance to stun the target for 3 sec.",
          [P_proc(used("warrior_revenge", [E("ApplyAura", aura="warrior_revenge_stun")]), values=[15, 30, 45])]),
        T(P + "defiance", "Defiance", "stance_defensive", 3, 3, 5,
          "Increases the threat generated by your attacks by {3/6/9/12/15}% while in Defensive Stance.",
          [P_special("WarriorDefiance", value=3)]),
        T(P + "improved_sunder_armor", "Improved Sunder Armor", "armor", 4, 0, 3,
          "Reduces the cost of your Sunder Armor ability by {1/2/3} rage points.",
          [P_mod("CostFlat", -1, abilities=["warrior_sunder_armor"])]),
        T(P + "improved_disarm", "Improved Disarm", "hand", 4, 1, 3,
          "Increases the duration of your Disarm ability by {1/2/3} secs.",
          [P_mod("Duration", 1, abilities=["warrior_disarm"])]),
        T(P + "improved_taunt", "Improved Taunt", "shout", 4, 2, 2,
          "Reduces the cooldown of your Taunt ability by {1/2} sec.",
          [P_mod("Cooldown", -1, abilities=["warrior_taunt"])]),
        T(P + "improved_shield_wall", "Improved Shield Wall", "shield", 5, 0, 2,
          "Increases the effect duration of your Shield Wall ability by {3/5} secs.",
          [P_mod("Duration", values=[3, 5], abilities=["warrior_shield_wall"])]),
        T(P + "concussion_blow", "Concussion Blow", "hammer", 5, 1, 1, "Grants the Concussion Blow ability.",
          [P_grant("warrior_concussion_blow")]),
        T(P + "improved_shield_bash", "Improved Shield Bash", "shield_bash", 5, 2, 2,
          "Gives your Shield Bash ability a {50/100}% chance to silence the target for 3 sec.",
          [P_proc(used("warrior_shield_bash", [E("ApplyAura", aura="warrior_shield_bash_silence")]), values=[50, 100])]),
        T(P + "one_handed_weapon_specialization", "One-Handed Weapon Specialization", "sword", 6, 2, 5,
          "Increases the damage you deal with one-handed melee weapons by {2/4/6/8/10}%.",
          [wtt(["OneHanded"], stat="DamageDone", value=2, pct=True)]),
        T(P + "shield_slam", "Shield Slam", "shield_bash", 7, 1, 1, "Grants the Shield Slam ability.",
          [P_grant("warrior_shield_slam")], requires=P + "concussion_blow"),
    ],
}

TREES = [ARMS, FURY, PROT]

# Must match classes/warrior.json defaultBuild exactly (class audit: Improved Rend -> Deep Wounds and
# Tactical Mastery -> Anger Management are arrow prerequisites, so both are maxed first).
BUILD = (
    [A + "improved_heroic_strike"] * 3 + [A + "improved_rend"] * 3 + [A + "tactical_mastery"] * 5 +
    [A + "anger_management"] + [A + "deep_wounds"] * 3 + [A + "impale"] * 2 +
    [A + "two_handed_weapon_specialization"] * 3 + [A + "sweeping_strikes"] + [A + "sword_specialization"] * 5 +
    [A + "two_handed_weapon_specialization"] * 2 + [A + "improved_overpower"] * 2 + [A + "mortal_strike"] +
    [F + "cruelty"] * 5 + [F + "unbridled_wrath"] * 5 + [F + "improved_battle_shout"] * 5 + [F + "booming_voice"] * 5
)
